-- Vocabulario extraído de 'El curso más completo de inglés' (Omar Ali Caldela)
-- Importar en Supabase → SQL Editor

INSERT INTO phrases (english, spanish, category, level) VALUES
  ('Teacher', 'maestro, profesor', 'Vocabulario del salón', 'A1'),
  ('Student', 'estudiante', 'Vocabulario del salón', 'A1'),
  ('Boy', 'niño, muchacho', 'Vocabulario del salón', 'A1'),
  ('Girl', 'niña, muchacha', 'Vocabulario del salón', 'A1'),
  ('Chair', 'silla', 'Vocabulario del salón', 'A1'),
  ('Book', 'libro', 'Vocabulario del salón', 'A1'),
  ('Table', 'mesa', 'Vocabulario del salón', 'A1'),
  ('Notebook', 'libreta', 'Vocabulario del salón', 'A1'),
  ('Pen', 'lapicero', 'Vocabulario del salón', 'A1'),
  ('Pencil', 'lápiz', 'Vocabulario del salón', 'A1'),
  ('Eraser', 'borrador', 'Vocabulario del salón', 'A1'),
  ('Chalk', 'gis, tiza', 'Vocabulario del salón', 'A1'),
  ('Blackboard', 'pizarrón', 'Vocabulario del salón', 'A1'),
  ('Chalkboard', 'pizarrón para gis', 'Vocabulario del salón', 'A1'),
  ('Marker', 'marcador', 'Vocabulario del salón', 'A1'),
  ('Pencil sharpener', 'sacapuntas', 'Vocabulario del salón', 'A1'),
  ('Rule', 'regla', 'Vocabulario del salón', 'A1'),
  ('Color', 'color', 'Vocabulario del salón', 'A1'),
  ('Sheet', 'hoja de cuaderno, lámina o sabana', 'Vocabulario del salón', 'A1'),
  ('Page', 'página', 'Vocabulario del salón', 'A1'),
  ('Wall', 'pared, muro', 'Vocabulario del salón', 'A1'),
  ('Classroom', 'salón de clases', 'Vocabulario del salón', 'A1'),
  ('Floor', 'piso', 'Vocabulario del salón', 'A1'),
  ('Window', 'ventana', 'Vocabulario del salón', 'A1'),
  ('Picture', 'cuadro, pintura, película', 'Vocabulario del salón', 'A1'),
  ('Poster', 'poster, cartel', 'Vocabulario del salón', 'A1'),
  ('Sign', 'signo, señal, símbolo', 'Vocabulario del salón', 'A1'),
  ('Paper', 'papel', 'Vocabulario del salón', 'A1'),
  ('Tape recorder', 'grabadora', 'Vocabulario del salón', 'A1'),
  ('Ceiling fan', 'ventilador de techo', 'Vocabulario del salón', 'A1'),
  ('Explanation', 'explicación', 'Vocabulario del salón', 'A1'),
  ('Doubt', 'duda', 'Vocabulario del salón', 'A1'),
  ('Pencil case', 'lapicera', 'Vocabulario del salón', 'A1'),
  ('Trash can', 'bote de basura', 'Vocabulario del salón', 'A1'),
  ('Card', 'tarjeta', 'Vocabulario del salón', 'A1'),
  ('Letter', 'carta "de correo"', 'Vocabulario del salón', 'A1'),
  ('In pencil', 'a lápiz', 'Vocabulario del salón', 'A1'),
  ('In ink', 'en o con tinta', 'Vocabulario del salón', 'A1'),
  ('Exam', 'examen', 'Vocabulario del salón', 'A1'),
  ('Door', 'puerta', 'Vocabulario del salón', 'A1'),
  ('Box', 'caja', 'Vocabulario del salón', 'A1'),
  ('Exercise', 'ejercicio', 'Vocabulario del salón', 'A1'),
  ('Homework', 'tarea', 'Vocabulario del salón', 'A1'),
  ('Lock', 'cerradura', 'Vocabulario del salón', 'A1'),
  ('Key', 'llave', 'Vocabulario del salón', 'A1'),
  ('Switch', 'interruptor', 'Vocabulario del salón', 'A1'),
  ('Plug', 'clavija', 'Vocabulario del salón', 'A1'),
  ('Rewinder', 'regresadora', 'Vocabulario del salón', 'A1'),
  ('Welcome class', 'bienvenido a clases', 'Vocabulario del salón', 'A1'),
  ('Flag', 'bandera', 'Vocabulario del salón', 'A1'),
  ('Clock', 'reloj "de pared"', 'Vocabulario del salón', 'A1'),
  ('Outlet', 'tomacorriente, enchufe', 'Vocabulario del salón', 'A1'),
  ('Game', 'juego', 'Vocabulario del salón', 'A1'),
  ('Loudspeaker', 'altavoz, bocina', 'Vocabulario del salón', 'A1'),
  ('Locker', 'armario', 'Vocabulario del salón', 'A1'),
  ('Telephone', 'teléfono', 'Vocabulario del salón', 'A1'),
  ('Bulletin board', 'tablero de edictos', 'Vocabulario del salón', 'A1'),
  ('Computer', 'computadora', 'Vocabulario del salón', 'A1'),
  ('Hall', 'pasillo', 'Vocabulario del salón', 'A1'),
  ('Loose leaf paper', 'hoja suelta de papel', 'Vocabulario del salón', 'A1'),
  ('Ring binder', 'carpeta', 'Vocabulario del salón', 'A1'),
  ('Spiral notebook', 'cuaderno de espiral', 'Vocabulario del salón', 'A1'),
  ('Glue', 'pegamento', 'Vocabulario del salón', 'A1'),
  ('Scissors', 'tijeras', 'Vocabulario del salón', 'A1'),
  ('Brush', 'brocha', 'Vocabulario del salón', 'A1'),
  ('Ballpoint pen', 'bolígrafo', 'Vocabulario del salón', 'A1'),
  ('Thumbtack', 'tachuela', 'Vocabulario del salón', 'A1'),
  ('Text book', 'libro de texto', 'Vocabulario del salón', 'A1'),
  ('Overhead projector', 'retroproyector', 'Vocabulario del salón', 'A1'),
  ('Practice', 'práctica', 'Vocabulario del salón', 'A1'),
  ('Study', 'estudio', 'Vocabulario del salón', 'A1'),
  ('Presentaciones Introductions', 'Presentaciones', 'Saludos y presentaciones', 'A1'),
  ('What is your name?', '¿Cuál es tu nombre?', 'Saludos y presentaciones', 'A1'),
  ('My name is', 'mi nombre es', 'Saludos y presentaciones', 'A1'),
  ('Who are you?', '¿Quién eres tú?', 'Saludos y presentaciones', 'A1'),
  ('I am', 'yo soy', 'Saludos y presentaciones', 'A1'),
  ('Where are you from?', '¿de dónde eres tú?', 'Saludos y presentaciones', 'A1'),
  ('I am from', 'yo soy de', 'Saludos y presentaciones', 'A1'),
  ('Nice to meet you!', '¡gusto conocerte!', 'Saludos y presentaciones', 'A1'),
  ('My pleasure!', '¡mi placer!, ¡es un placer!', 'Saludos y presentaciones', 'A1'),
  ('Nice to see you!', '¡gusto verte!', 'Saludos y presentaciones', 'A1'),
  ('Again', 'otra vez, de nuevo', 'Saludos y presentaciones', 'A1'),
  ('Now', 'ahora', 'Saludos y presentaciones', 'A1'),
  ('This is my friend', 'este es mi amigo', 'Saludos y presentaciones', 'A1'),
  ('Too', 'también', 'Saludos y presentaciones', 'A1'),
  ('I´m glad to meet you!', '¡estoy contento de conocerte!', 'Saludos y presentaciones', 'A1'),
  ('It is a pleasure to meet you!', '¡es un placer conocerte!', 'Saludos y presentaciones', 'A1'),
  ('I´m sorry', 'lo siento, perdone', 'Saludos y presentaciones', 'A1'),
  ('Excuse me', 'excúseme, disculpe', 'Saludos y presentaciones', 'A1'),
  ('Greetings', 'saludos', 'Saludos y presentaciones', 'A1'),
  ('Hello!', '¡hola!', 'Saludos y presentaciones', 'A1'),
  ('How are you?', '¿cómo estas tu?', 'Saludos y presentaciones', 'A1'),
  ('I´m fine', 'estoy bien', 'Saludos y presentaciones', 'A1'),
  ('I´m very well', 'estoy muy bien', 'Saludos y presentaciones', 'A1'),
  ('I am not', 'yo no estoy', 'Saludos y presentaciones', 'A1'),
  ('How do you do!', '¡como te va!', 'Saludos y presentaciones', 'A1'),
  ('How you doing!', '¡como te va!', 'Saludos y presentaciones', 'A1'),
  ('How´ve you been!', '¡como has estado!', 'Saludos y presentaciones', 'A1'),
  ('I´ve been', 'yo he estado', 'Saludos y presentaciones', 'A1'),
  ('Good morning', 'buen día', 'Saludos y presentaciones', 'A1'),
  ('Good afternoon', 'buena tarde', 'Saludos y presentaciones', 'A1'),
  ('Good evening', 'buena noche', 'Saludos y presentaciones', 'A1'),
  ('What´s new!', '¡que hay de nuevo!', 'Saludos y presentaciones', 'A1'),
  ('What´s up', '¡Que pasa!', 'Saludos y presentaciones', 'A1'),
  ('What happens!', '¡Que pasa!', 'Saludos y presentaciones', 'A1'),
  ('Leave takings', 'despedidas', 'Saludos y presentaciones', 'A1'),
  ('See you later', 'te veo mas tarde', 'Saludos y presentaciones', 'A1'),
  ('See you around', 'te veo de vuelta', 'Saludos y presentaciones', 'A1'),
  ('So long', 'hasta luego', 'Saludos y presentaciones', 'A1'),
  ('Until tomorrow', 'hasta mañana', 'Saludos y presentaciones', 'A1'),
  ('I have to go now', 'yo tengo que irme ahora', 'Saludos y presentaciones', 'A1'),
  ('Good night', 'buena noche', 'Saludos y presentaciones', 'A1'),
  ('Good bye', 'adiós', 'Saludos y presentaciones', 'A1'),
  ('To study', 'estudiar', 'Verbos y pronombres', 'A1'),
  ('To teach', 'enseñar "un conocimiento o habilidad"', 'Verbos y pronombres', 'A1'),
  ('To learn', 'aprender', 'Verbos y pronombres', 'A1'),
  ('To practice', 'practicar', 'Verbos y pronombres', 'A1'),
  ('To go', 'ir', 'Verbos y pronombres', 'A1'),
  ('To come', 'venir', 'Verbos y pronombres', 'A1'),
  ('To watch', 'observar', 'Verbos y pronombres', 'A1'),
  ('To see', 'mirar, ver', 'Verbos y pronombres', 'A1'),
  ('To open', 'abrir', 'Verbos y pronombres', 'A1'),
  ('To work', 'trabajar', 'Verbos y pronombres', 'A1'),
  ('To love', 'amar', 'Verbos y pronombres', 'A1'),
  ('To want', 'querer "de obtener"', 'Verbos y pronombres', 'A1'),
  ('To have', 'tener', 'Verbos y pronombres', 'A1'),
  ('To be', 'ser, estar', 'Verbos y pronombres', 'A1'),
  ('Subject pronouns', 'personas del sujeto', 'Verbos y pronombres', 'A1'),
  ('You', 'tú o usted; ustedes', 'Verbos y pronombres', 'A1'),
  ('We', 'nosotros / as', 'Verbos y pronombres', 'A1'),
  ('They', 'ellos / ellas', 'Verbos y pronombres', 'A1'),
  ('He', 'él', 'Verbos y pronombres', 'A1'),
  ('She', 'ella', 'Verbos y pronombres', 'A1'),
  ('It', 'representa a una cosa o a un animal', 'Verbos y pronombres', 'A1'),
  ('O mouse', 'ratón', 'Verbos y pronombres', 'A1'),
  ('To have a job is easy', 'tener un trabajo es fácil', 'Verbos y pronombres', 'A1'),
  ('Baby', 'bebe', 'Sustantivos', 'A1'),
  ('Home', 'hogar', 'Sustantivos', 'A1'),
  ('Friend', 'amigo', 'Sustantivos', 'A1'),
  ('House', 'casa', 'Sustantivos', 'A1'),
  ('Fruit', 'fruta', 'Sustantivos', 'A1'),
  ('Kiss', 'beso', 'Sustantivos', 'A1'),
  ('Name', 'nombre', 'Sustantivos', 'A1'),
  ('Lettuce', 'lechuga', 'Sustantivos', 'A1'),
  ('Sentence', 'oración', 'Sustantivos', 'A1'),
  ('Dog', 'perro', 'Sustantivos', 'A1'),
  ('Radish', 'rábano', 'Sustantivos', 'A1'),
  ('Tomato', 'tomate', 'Sustantivos', 'A1'),
  ('Celery', 'apio', 'Sustantivos', 'A1'),
  ('Day', 'día', 'Sustantivos', 'A1'),
  ('Knife', 'cuchillo', 'Sustantivos', 'A1'),
  ('Leaf', 'hoja "de árbol"', 'Sustantivos', 'A1'),
  ('Handkerchif', 'pañuelo', 'Sustantivos', 'A1'),
  ('Roof', 'techo, azotea', 'Sustantivos', 'A1'),
  ('Proof', 'prueba, evidencia', 'Sustantivos', 'A1'),
  ('Cuff', 'dobles de un pantalón o camisa; bofetada', 'Sustantivos', 'A1'),
  ('Woman', 'mujer', 'Sustantivos', 'A1'),
  ('Child', 'niño /a', 'Sustantivos', 'A1'),
  ('Foot', 'pie', 'Sustantivos', 'A1'),
  ('Tooth', 'diente', 'Sustantivos', 'A1'),
  ('Goose', 'ganso', 'Sustantivos', 'A1'),
  ('Mouse', 'ratón', 'Sustantivos', 'A1'),
  ('Ox', 'buey', 'Sustantivos', 'A1'),
  ('Deer', 'venado', 'Sustantivos', 'A1'),
  ('Sheep', 'oveja', 'Sustantivos', 'A1'),
  ('Person', 'persona', 'Sustantivos', 'A1'),
  ('Address book', 'libreta de direcciones', 'Sustantivos', 'A1'),
  ('Big', 'grande', 'Sustantivos', 'A1'),
  ('Low', 'bajo', 'Sustantivos', 'A1'),
  ('Tall', 'alto / a', 'Sustantivos', 'A1'),
  ('Short', 'corto', 'Sustantivos', 'A1'),
  ('Fat', 'gordo', 'Sustantivos', 'A1'),
  ('Interesting', 'interesante', 'Sustantivos', 'A1'),
  ('Blue', 'azul', 'Sustantivos', 'A1'),
  ('Blonde', 'rubia', 'Sustantivos', 'A1'),
  ('Workable', 'manejable, trabajable, maleable (adj', 'Sustantivos', 'A1'),
  ('Playful', 'jugeton /ona', 'Sustantivos', 'A1'),
  ('Asleep', 'dormido / a', 'Sustantivos', 'A1'),
  ('Opening', 'apertura', 'Sustantivos', 'A1'),
  ('He is tired', 'él esta cansado', 'Sustantivos', 'A1'),
  ('We are bored', 'nosotros estamos aburridos', 'Sustantivos', 'A1'),
  ('You interested in', 'interesado en', 'Sustantivos', 'A1'),
  ('She tired', 'cansado', 'Sustantivos', 'A1'),
  ('It am/is/are relaxed', 'relajado', 'Sustantivos', 'A1'),
  ('We worried', 'preocupado', 'Sustantivos', 'A1'),
  ('They confused', 'confundido', 'Sustantivos', 'A1'),
  ('Soft music is relaxing', 'la música suave es relajante', 'Sustantivos', 'A1'),
  ('That is a confusing movie', 'esa es una película confusa', 'Sustantivos', 'A1'),
  ('Correctly', 'correctamente', 'Adverbios y artículos', 'A1'),
  ('Only', 'solamente, solo', 'Adverbios y artículos', 'A1'),
  ('Finally', 'finalmente', 'Adverbios y artículos', 'A1'),
  ('Fast', 'rápidamente', 'Adverbios y artículos', 'A1'),
  ('He smells bad', 'el huele mal', 'Adverbios y artículos', 'A1'),
  ('The dog seems tired', 'el perro parece cansado', 'Adverbios y artículos', 'A1'),
  ('They look angry', 'ellos lucen enojados', 'Adverbios y artículos', 'A1'),
  ('The soup tastes wonderful', 'la sopa sabe maravillosa', 'Adverbios y artículos', 'A1'),
  ('The exam seems to be difficult', 'el examen parece estar dificil', 'Adverbios y artículos', 'A1'),
  ('To', 'a, hacia, "indica dirección"', 'Adverbios y artículos', 'A1'),
  ('In', 'en, dentro', 'Adverbios y artículos', 'A1'),
  ('On', 'en, sobre, encima', 'Adverbios y artículos', 'A1'),
  ('At', 'en, "indica posición permanente"', 'Adverbios y artículos', 'A1'),
  ('Inside', 'dentro de', 'Adverbios y artículos', 'A1'),
  ('Outside', 'fuera de', 'Adverbios y artículos', 'A1'),
  ('Before', 'antes', 'Adverbios y artículos', 'A1'),
  ('After', 'después', 'Adverbios y artículos', 'A1'),
  ('Without', 'sin', 'Adverbios y artículos', 'A1'),
  ('But', 'pero', 'Adverbios y artículos', 'A1'),
  ('Because', 'porque', 'Adverbios y artículos', 'A1'),
  ('People', 'la gente', 'Adverbios y artículos', 'A1'),
  ('The boy in the house', 'los niños en la casa', 'Adverbios y artículos', 'A1'),
  ('To open a box', 'abrir una caja', 'Adverbios y artículos', 'A1'),
  ('I work', 'yo trabajo', 'Adverbios y artículos', 'A1'),
  ('She opens', 'ella abre', 'Adverbios y artículos', 'A1'),
  ('The alphabet', 'el alfabeto', 'Verbos regulares', 'A1'),
  ('The vowels', 'las vocales', 'Verbos regulares', 'A1'),
  ('Cuestion', 'pregunta', 'Verbos regulares', 'A1'),
  ('Answer', 'respuesta', 'Verbos regulares', 'A1'),
  ('How do you spell your name?', '¿cómo deletrea usted su nombre?', 'Verbos regulares', 'A1'),
  ('Actions', 'acciones', 'Verbos regulares', 'A1'),
  ('Accept', 'aceptar', 'Verbos regulares', 'A1'),
  ('Achieve', 'lograr', 'Verbos regulares', 'A1'),
  ('Act', 'actuar', 'Verbos regulares', 'A1'),
  ('Add', 'agregar', 'Verbos regulares', 'A1'),
  ('Admit', 'admitir', 'Verbos regulares', 'A1'),
  ('Agree', 'acordar, estar de acuerdo', 'Verbos regulares', 'A1'),
  ('Allow', 'permitir', 'Verbos regulares', 'A1'),
  ('Announce', 'anunciar', 'Verbos regulares', 'A1'),
  ('Annoy', 'irritar, molestar', 'Verbos regulares', 'A1'),
  ('Appear', 'aparecer, parecer', 'Verbos regulares', 'A1'),
  ('Argue', 'argumentar, discutir', 'Verbos regulares', 'A1'),
  ('Ask', 'preguntar, pedir', 'Verbos regulares', 'A1'),
  ('Assume', 'asumir', 'Verbos regulares', 'A1'),
  ('Attack', 'atacar', 'Verbos regulares', 'A1'),
  ('Attend', 'asistir a', 'Verbos regulares', 'A1'),
  ('Avoid', 'evitar', 'Verbos regulares', 'A1'),
  ('Arrive', 'llegar', 'Verbos regulares', 'A1'),
  ('Believe', 'creer', 'Verbos regulares', 'A1'),
  ('Bother', 'molestar', 'Verbos regulares', 'A1'),
  ('Burn', 'quemar', 'Verbos regulares', 'A1'),
  ('Call', 'llamar', 'Verbos regulares', 'A1'),
  ('Cancel', 'cancelar', 'Verbos regulares', 'A1'),
  ('Care', 'preocuparse', 'Verbos regulares', 'A1'),
  ('Carry', 'llevar, cargar', 'Verbos regulares', 'A1'),
  ('Cause', 'causar', 'Verbos regulares', 'A1'),
  ('Change', 'cambiar', 'Verbos regulares', 'A1'),
  ('Clap', 'aplaudir', 'Verbos regulares', 'A1'),
  ('Commit', 'cometer', 'Verbos regulares', 'A1'),
  ('Compare', 'comparar', 'Verbos regulares', 'A1'),
  ('Connect', 'conectar', 'Verbos regulares', 'A1'),
  ('Consider', 'considerar', 'Verbos regulares', 'A1'),
  ('Contain', 'contener', 'Verbos regulares', 'A1'),
  ('Continue', 'continuar', 'Verbos regulares', 'A1'),
  ('Control', 'controlar', 'Verbos regulares', 'A1'),
  ('Create', 'crear', 'Verbos regulares', 'A1'),
  ('Cry', 'llorar', 'Verbos regulares', 'A1'),
  ('Check', 'checar', 'Verbos regulares', 'A1'),
  ('Clean', 'limpiar', 'Verbos regulares', 'A1'),
  ('Climb', 'subir, trepar', 'Verbos regulares', 'A1'),
  ('Cook', 'cocinar', 'Verbos regulares', 'A1'),
  ('Close', 'cerrar', 'Verbos regulares', 'A1'),
  ('Count', 'contar', 'Verbos regulares', 'A1'),
  ('Cover', 'cubrir, tapar', 'Verbos regulares', 'A1'),
  ('Deliver', 'entregar, repartir', 'Verbos regulares', 'A1'),
  ('Dare', 'atreverse', 'Verbos regulares', 'A1'),
  ('Describe', 'describir', 'Verbos regulares', 'A1'),
  ('Design', 'diseñar', 'Verbos regulares', 'A1'),
  ('Dial', 'marcar "un número telefonico"', 'Verbos regulares', 'A1'),
  ('Discover', 'descubrir', 'Verbos regulares', 'A1'),
  ('Discuss', 'discutir', 'Verbos regulares', 'A1'),
  ('Dance', 'bailar, danzar', 'Verbos regulares', 'A1'),
  ('Date', 'fechar, salir con', 'Verbos regulares', 'A1'),
  ('Decide', 'decidir', 'Verbos regulares', 'A1'),
  ('Develop', 'desarrollar "una tierra, una enfermedad, una idea, una película, etc', 'Verbos regulares', 'A1'),
  ('Distribute', 'distribuir, diseminar', 'Verbos regulares', 'A1'),
  ('Dress', 'vestir, vestirse', 'Verbos regulares', 'A1'),
  ('Drop', 'dejar caer', 'Verbos regulares', 'A1'),
  ('End', 'finalizar', 'Verbos regulares', 'A1'),
  ('Enjoy', 'disfrutar', 'Verbos regulares', 'A1'),
  ('Escape', 'escapar', 'Verbos regulares', 'A1'),
  ('Earn', 'ganar "dinero"', 'Verbos regulares', 'A1'),
  ('Enter', 'entrar', 'Verbos regulares', 'A1'),
  ('Excuse', 'disculpar "de interrumpir"', 'Verbos regulares', 'A1'),
  ('Expect', 'esperar', 'Verbos regulares', 'A1'),
  ('Explain', 'explicar', 'Verbos regulares', 'A1'),
  ('Express', 'expresar', 'Verbos regulares', 'A1'),
  ('Finish', 'terminar', 'Verbos regulares', 'A1'),
  ('Fix', 'arreglar, reparar', 'Verbos regulares', 'A1'),
  ('Follow', 'seguir', 'Verbos regulares', 'A1'),
  ('Face', 'enfrentar', 'Verbos regulares', 'A1'),
  ('Force', 'forzar', 'Verbos regulares', 'A1'),
  ('Fry', 'freir', 'Verbos regulares', 'A1'),
  ('Guess', 'adivinar, pensar', 'Verbos regulares', 'A1'),
  ('Help', 'ayudar', 'Verbos regulares', 'A1'),
  ('Handle', 'encargarse de', 'Verbos regulares', 'A1'),
  ('Hate', 'odiar', 'Verbos regulares', 'A1'),
  ('Hope', 'esperar "un deseo"', 'Verbos regulares', 'A1'),
  ('Hug', 'abrazar', 'Verbos regulares', 'A1'),
  ('Include', 'incluir', 'Verbos regulares', 'A1'),
  ('Intend', 'pretender "hacer algo"', 'Verbos regulares', 'A1'),
  ('Imagine', 'imaginar', 'Verbos regulares', 'A1'),
  ('Improve', 'mejorar', 'Verbos regulares', 'A1'),
  ('Increase', 'aumentar', 'Verbos regulares', 'A1'),
  ('Jump', 'saltar', 'Verbos regulares', 'A1'),
  ('Join', 'unir', 'Verbos regulares', 'A1'),
  ('Knock', 'golpear', 'Verbos regulares', 'A1'),
  ('Learn', 'aprender', 'Verbos regulares', 'A1'),
  ('Like', 'gustar', 'Verbos regulares', 'A1'),
  ('Listen to', 'escuchar a', 'Verbos regulares', 'A1'),
  ('Live', 'vivir', 'Verbos regulares', 'A1'),
  ('Look at', 'mirar a', 'Verbos regulares', 'A1'),
  ('Love', 'amar', 'Verbos regulares', 'A1'),
  ('Lie', 'mentir', 'Verbos regulares', 'A1'),
  ('Light', 'prender', 'Verbos regulares', 'A1'),
  ('Miss', 'extrañar, errar, perder "una oportunidad"', 'Verbos regulares', 'A1'),
  ('Mark', 'marcar', 'Verbos regulares', 'A1'),
  ('Measure', 'medir', 'Verbos regulares', 'A1'),
  ('Move', 'mover', 'Verbos regulares', 'A1'),
  ('Need', 'necesitar', 'Verbos regulares', 'A1'),
  ('Note', 'anotar', 'Verbos regulares', 'A1'),
  ('Notice', 'notar, darse cuenta', 'Verbos regulares', 'A1'),
  ('Open', 'abrir', 'Verbos regulares', 'A1'),
  ('Order', 'ordenar, pedir', 'Verbos regulares', 'A1'),
  ('Observe', 'observar', 'Verbos regulares', 'A1'),
  ('Obtain', 'obtener', 'Verbos regulares', 'A1'),
  ('Offer', 'ofrecer', 'Verbos regulares', 'A1'),
  ('Operate', 'operar', 'Verbos regulares', 'A1'),
  ('Pass', 'pasar', 'Verbos regulares', 'A1'),
  ('Pat', 'dar palmaditas a, acariciar', 'Verbos regulares', 'A1'),
  ('Permit', 'permitir', 'Verbos regulares', 'A1'),
  ('Place', 'colocar', 'Verbos regulares', 'A1'),
  ('Plan', 'hacer planes, planear', 'Verbos regulares', 'A1'),
  ('Point', 'apuntar', 'Verbos regulares', 'A1'),
  ('Pray', 'rezar', 'Verbos regulares', 'A1'),
  ('Plant', 'plantar', 'Verbos regulares', 'A1'),
  ('Play', 'jugar, representar "una actuacion", tocar "un instrumento', 'Verbos regulares', 'A1'),
  ('Prefer', 'preferir', 'Verbos regulares', 'A1'),
  ('Push', 'empujar', 'Verbos regulares', 'A1'),
  ('Pull', 'jalar', 'Verbos regulares', 'A1'),
  ('Prepare', 'preparar', 'Verbos regulares', 'A1'),
  ('Present', 'presentar', 'Verbos regulares', 'A1'),
  ('Prevent', 'prevenir', 'Verbos regulares', 'A1'),
  ('Proceed', 'proceder', 'Verbos regulares', 'A1'),
  ('Produce', 'producir', 'Verbos regulares', 'A1'),
  ('Program', 'programar', 'Verbos regulares', 'A1'),
  ('Prove', 'probar, demostrar', 'Verbos regulares', 'A1'),
  ('Put', 'poner', 'Verbos regulares', 'A1'),
  ('Rain', 'llover', 'Verbos regulares', 'A1'),
  ('Raise', 'elevar', 'Verbos regulares', 'A1'),
  ('Reach', 'alcanzar "un objeto o un lugar"', 'Verbos regulares', 'A1'),
  ('React', 'reaccionar', 'Verbos regulares', 'A1'),
  ('Receive', 'recibir', 'Verbos regulares', 'A1'),
  ('Recognize', 'reconocer', 'Verbos regulares', 'A1'),
  ('Reduce', 'reducir', 'Verbos regulares', 'A1'),
  ('Recommend', 'recomendar', 'Verbos regulares', 'A1'),
  ('Regret', 'lamentar', 'Verbos regulares', 'A1'),
  ('Remember', 'recordar, acordarse de', 'Verbos regulares', 'A1'),
  ('Rent', 'rentar', 'Verbos regulares', 'A1'),
  ('Reply', 'responder, contestar', 'Verbos regulares', 'A1'),
  ('Report', 'reportar', 'Verbos regulares', 'A1'),
  ('Represent', 'representar', 'Verbos regulares', 'A1'),
  ('Rescue', 'rescatar', 'Verbos regulares', 'A1'),
  ('Rest', 'descansar', 'Verbos regulares', 'A1'),
  ('Return', 'retroceder', 'Verbos regulares', 'A1'),
  ('Rob', 'robar', 'Verbos regulares', 'A1'),
  ('Rub', 'frotar', 'Verbos regulares', 'A1'),
  ('Repair', 'reparar', 'Verbos regulares', 'A1'),
  ('Repeat', 'repetir', 'Verbos regulares', 'A1'),
  ('Save', 'ahorrar, salvar', 'Verbos regulares', 'A1'),
  ('Seem', 'parecer', 'Verbos regulares', 'A1'),
  ('Scare', 'asustar', 'Verbos regulares', 'A1'),
  ('Serve', 'servir', 'Verbos regulares', 'A1'),
  ('Shape', 'moldear, formar', 'Verbos regulares', 'A1'),
  ('Shave', 'rasurar', 'Verbos regulares', 'A1'),
  ('Shop', 'comprar', 'Verbos regulares', 'A1'),
  ('Show', 'mostrar, enseñar', 'Verbos regulares', 'A1'),
  ('Shut', 'cerrar, trancar', 'Verbos regulares', 'A1'),
  ('Slip', 'deslizar', 'Verbos regulares', 'A1'),
  ('Smell', 'oler', 'Verbos regulares', 'A1'),
  ('Smile', 'sonreir', 'Verbos regulares', 'A1'),
  ('Sound', 'sonar', 'Verbos regulares', 'A1'),
  ('Spell', 'deletrear', 'Verbos regulares', 'A1'),
  ('Spill', 'derramar', 'Verbos regulares', 'A1'),
  ('Stare', 'mirar fijamente', 'Verbos regulares', 'A1'),
  ('Step', 'pisar', 'Verbos regulares', 'A1'),
  ('Smoke', 'fumar', 'Verbos regulares', 'A1'),
  ('Start', 'comenzar, empezar', 'Verbos regulares', 'A1'),
  ('Stay', 'permanecer, quedarse', 'Verbos regulares', 'A1'),
  ('Stroke', 'acariciar "a un animal"', 'Verbos regulares', 'A1'),
  ('Suggest', 'sugerir', 'Verbos regulares', 'A1'),
  ('Support', 'apoyar', 'Verbos regulares', 'A1'),
  ('Suppose', 'suponer', 'Verbos regulares', 'A1'),
  ('Surprise', 'sorprender', 'Verbos regulares', 'A1'),
  ('Talk to', 'hablar con / a', 'Verbos regulares', 'A1'),
  ('Travel', 'viajar', 'Verbos regulares', 'A1'),
  ('Try', 'intentar, probar', 'Verbos regulares', 'A1'),
  ('Turn', 'girar, voltear, dar la vuelta a', 'Verbos regulares', 'A1'),
  ('Tie', 'amarrar', 'Verbos regulares', 'A1'),
  ('Treat', 'tratar, convidar', 'Verbos regulares', 'A1'),
  ('Taste', 'probar, notar un sabor "saber"', 'Verbos regulares', 'A1'),
  ('Touch', 'tocar, palpar', 'Verbos regulares', 'A1'),
  ('Use', 'usar', 'Verbos regulares', 'A1'),
  ('Visit', 'visitar', 'Verbos regulares', 'A1'),
  ('Vote', 'votar "de elección"', 'Verbos regulares', 'A1'),
  ('Wait for', 'esperar por / a', 'Verbos regulares', 'A1'),
  ('Walk', 'caminar', 'Verbos regulares', 'A1'),
  ('Want', 'querer "de conseguir"', 'Verbos regulares', 'A1'),
  ('Wash', 'lavar', 'Verbos regulares', 'A1'),
  ('Watch', 'observar', 'Verbos regulares', 'A1'),
  ('Work', 'trabajar', 'Verbos regulares', 'A1'),
  ('Wish', 'desear', 'Verbos regulares', 'A1'),
  ('Worry', 'preocuparse', 'Verbos regulares', 'A1'),
  ('Wound', 'herir, lastimar', 'Verbos regulares', 'A1'),
  ('Wrap', 'envolver', 'Verbos regulares', 'A1'),
  ('Abide', 'aguantar, soportar', 'Verbos irregulares', 'A2'),
  ('Arise', 'surgir', 'Verbos irregulares', 'A2'),
  ('Awake', 'despertar', 'Verbos irregulares', 'A2'),
  ('Be', 'ser, estar', 'Verbos irregulares', 'A2'),
  ('Bear', 'soportar, aguantar, dar a luz', 'Verbos irregulares', 'A2'),
  ('Beat', 'golpear, vencer, batir, latir', 'Verbos irregulares', 'A2'),
  ('Become', 'convertirse, hacerse, ponerse, llegar a ser', 'Verbos irregulares', 'A2'),
  ('Begin', 'comenzar', 'Verbos irregulares', 'A2'),
  ('Bend', 'doblar, doblarse', 'Verbos irregulares', 'A2'),
  ('Bet', 'apostar', 'Verbos irregulares', 'A2'),
  ('Bind', 'atar, unir, encuadernar, obligar "en la ley"', 'Verbos irregulares', 'A2'),
  ('Bite', 'morder, picar', 'Verbos irregulares', 'A2'),
  ('Bleed', 'sangrar, vaciar', 'Verbos irregulares', 'A2'),
  ('Blow', 'soplar, hacer sonar, volar "de explotar"', 'Verbos irregulares', 'A2'),
  ('Break', 'romper, quebrar', 'Verbos irregulares', 'A2'),
  ('Breed', 'criar, cultivar, reproducirse', 'Verbos irregulares', 'A2'),
  ('Bring', 'traer', 'Verbos irregulares', 'A2'),
  ('Build', 'construir, edificar', 'Verbos irregulares', 'A2'),
  ('Buy', 'comprar', 'Verbos irregulares', 'A2'),
  ('Can', 'poder', 'Verbos irregulares', 'A2'),
  ('Cast', 'lanzar, echar, emitir, fundir "un metal", mudar "una piel", etc', 'Verbos irregulares', 'A2'),
  ('Choose', 'elegir, escoger', 'Verbos irregulares', 'A2'),
  ('Cling to', 'agarrarse, aferrarse', 'Verbos irregulares', 'A2'),
  ('Clothe', 'vestir', 'Verbos irregulares', 'A2'),
  ('Come', 'venir, llegar', 'Verbos irregulares', 'A2'),
  ('Cost', 'costar', 'Verbos irregulares', 'A2'),
  ('Creep', 'arrastrarse, avanzar lentamente', 'Verbos irregulares', 'A2'),
  ('Cut', 'cortar', 'Verbos irregulares', 'A2'),
  ('Deal', 'tratar, comerciar, repartir o dar "cartas"', 'Verbos irregulares', 'A2'),
  ('Dig', 'escarbar, excavar, cavar', 'Verbos irregulares', 'A2'),
  ('Dive', 'sumergirse, zambullirse, bucear, lanzarse en picada', 'Verbos irregulares', 'A2'),
  ('Do', 'hacer "una actividad fisica o mental"', 'Verbos irregulares', 'A2'),
  ('Draw', 'dibujar, trazar, desenfundar "un arma", etc', 'Verbos irregulares', 'A2'),
  ('Dream', 'soñar', 'Verbos irregulares', 'A2'),
  ('Drink', 'tomar, beber', 'Verbos irregulares', 'A2'),
  ('Drive', 'conducir, manejar, llevar en coche a alguien, arrear', 'Verbos irregulares', 'A2'),
  ('Dwell', 'morar, habitar', 'Verbos irregulares', 'A2'),
  ('Eat', 'comer', 'Verbos irregulares', 'A2'),
  ('Fall', 'caer', 'Verbos irregulares', 'A2'),
  ('Feed', 'alimentar, dar de comer a', 'Verbos irregulares', 'A2'),
  ('Feel', 'sentir', 'Verbos irregulares', 'A2'),
  ('Fight', 'pelear, combatir, luchar contra, pelearse', 'Verbos irregulares', 'A2'),
  ('Find', 'encontrar, descubrir', 'Verbos irregulares', 'A2'),
  ('Flee', 'huir de', 'Verbos irregulares', 'A2'),
  ('Fling', 'arrojar "de aventarse"', 'Verbos irregulares', 'A2'),
  ('Fly', 'volar, pilotear, hacer volar', 'Verbos irregulares', 'A2'),
  ('Forbid', 'prohibir', 'Verbos irregulares', 'A2'),
  ('Forget', 'olvidar, olvidarse', 'Verbos irregulares', 'A2'),
  ('Freeze', 'helar, congelar, helarse, congelarse', 'Verbos irregulares', 'A2'),
  ('Get', 'obtener, conseguir, ponerse', 'Verbos irregulares', 'A2'),
  ('Give', 'dar', 'Verbos irregulares', 'A2'),
  ('Go', 'ir', 'Verbos irregulares', 'A2'),
  ('Grind', 'moler, rechinar "dientes"', 'Verbos irregulares', 'A2'),
  ('Grow', 'crecer, volverse o ponerse, cultivar, dejarse crecer "la barba o el cabello"', 'Verbos irregulares', 'A2'),
  ('Hang', 'colgar, ahorcar', 'Verbos irregulares', 'A2'),
  ('Have', 'tener', 'Verbos irregulares', 'A2'),
  ('Hear', 'oír', 'Verbos irregulares', 'A2'),
  ('Hew', 'tallar "una estatua" o talar "árboles"', 'Verbos irregulares', 'A2'),
  ('Hide', 'esconder, ocultar', 'Verbos irregulares', 'A2'),
  ('Hit', 'pegar, golpear', 'Verbos irregulares', 'A2'),
  ('Hold', 'aguantar, sostener', 'Verbos irregulares', 'A2'),
  ('Hurt', 'hacer daño, herir, doler', 'Verbos irregulares', 'A2'),
  ('Keep', 'mantener, conservar, seguir "haciendo algo"', 'Verbos irregulares', 'A2'),
  ('Kneel', 'arrodillarse', 'Verbos irregulares', 'A2'),
  ('Knit', 'tejer, hacer punto de costura', 'Verbos irregulares', 'A2'),
  ('Know', 'saber, conocer', 'Verbos irregulares', 'A2'),
  ('Lay', 'colocar, poner', 'Verbos irregulares', 'A2'),
  ('Lead', 'dirigir, guiar, estar al frente de, encabezar', 'Verbos irregulares', 'A2'),
  ('Leave', 'dejar, salir', 'Verbos irregulares', 'A2'),
  ('Lend', 'prestar', 'Verbos irregulares', 'A2'),
  ('Let', 'dejar, permitir', 'Verbos irregulares', 'A2'),
  ('Lose', 'perder "en una competencia, de kilos"', 'Verbos irregulares', 'A2'),
  ('Make', 'hacer "manualidades o de fabricación"', 'Verbos irregulares', 'A2'),
  ('Mean', 'querer decir, significar, referirse a, tener la intención de', 'Verbos irregulares', 'A2'),
  ('Meet', 'encontrarse con, reunirse con, conocer por primera vez', 'Verbos irregulares', 'A2'),
  ('Mistake', 'equivocar, entender mal, errar', 'Verbos irregulares', 'A2'),
  ('Mow', 'cortar el pasto, podar', 'Verbos irregulares', 'A2'),
  ('Pay', 'pagar', 'Verbos irregulares', 'A2'),
  ('Quit', 'parar o dejar "de hacer algo"', 'Verbos irregulares', 'A2'),
  ('Read', 'leer', 'Verbos irregulares', 'A2'),
  ('Rid', 'librar, librarse', 'Verbos irregulares', 'A2'),
  ('Ride', 'montar "en un carro, bici, caballo, etc', 'Verbos irregulares', 'A2'),
  ('Ring', 'sonar', 'Verbos irregulares', 'A2'),
  ('Rise', 'elevarse', 'Verbos irregulares', 'A2'),
  ('Run', 'correr, administrar, dirigir, organizar', 'Verbos irregulares', 'A2'),
  ('Saw', 'serrar, cortar con una sierra', 'Verbos irregulares', 'A2'),
  ('Say', 'decir', 'Verbos irregulares', 'A2'),
  ('See', 'ver', 'Verbos irregulares', 'A2'),
  ('Seek', 'buscar, solicitar', 'Verbos irregulares', 'A2'),
  ('Sell', 'vender', 'Verbos irregulares', 'A2'),
  ('Send', 'mandar, enviar', 'Verbos irregulares', 'A2'),
  ('Set', 'poner, colocar, hacer funcionar, programar', 'Verbos irregulares', 'A2'),
  ('Sew', 'cocer', 'Verbos irregulares', 'A2'),
  ('Shake', 'sacudir', 'Verbos irregulares', 'A2'),
  ('Shed', 'despojarse de, deshacerse de, perder, derramar', 'Verbos irregulares', 'A2'),
  ('Shoot', 'disparar', 'Verbos irregulares', 'A2'),
  ('Shred', 'hacer trizas "un papel", rallar "un alimento"', 'Verbos irregulares', 'A2'),
  ('Shrink', 'encoger', 'Verbos irregulares', 'A2'),
  ('Sing', 'cantar', 'Verbos irregulares', 'A2'),
  ('Sink', 'hundir, hundirse', 'Verbos irregulares', 'A2'),
  ('Sit', 'sentarse', 'Verbos irregulares', 'A2'),
  ('Slay', 'asesinar, matar', 'Verbos irregulares', 'A2'),
  ('Sleep', 'dormir', 'Verbos irregulares', 'A2'),
  ('Slide', 'deslizar, deslizarse', 'Verbos irregulares', 'A2'),
  ('Slink', 'escabullirse', 'Verbos irregulares', 'A2'),
  ('Sow', 'plantar, sembrar', 'Verbos irregulares', 'A2'),
  ('Speak to', 'hablar a / con', 'Verbos irregulares', 'A2'),
  ('Speed', 'acelerar, ir con mucha rapidez', 'Verbos irregulares', 'A2'),
  ('Spend', 'gastar "tiempo y dinero"', 'Verbos irregulares', 'A2'),
  ('Spin', 'girar, dar vueltas a', 'Verbos irregulares', 'A2'),
  ('Spit', 'escupir', 'Verbos irregulares', 'A2'),
  ('Split', 'partir, separarse en dos', 'Verbos irregulares', 'A2'),
  ('Spoil', 'estropear, echar a perder', 'Verbos irregulares', 'A2'),
  ('Spread', 'extender, desplegar, estirar, untar', 'Verbos irregulares', 'A2'),
  ('Spring', 'saltar, moverse de repente', 'Verbos irregulares', 'A2'),
  ('Stand', 'colocar verticalmente algo, soportar "un dolor o carácter", levantarse o ponerse de pie', 'Verbos irregulares', 'A2'),
  ('Steal', 'robar, apropiarse de', 'Verbos irregulares', 'A2'),
  ('Stick', 'pegar, adherir', 'Verbos irregulares', 'A2'),
  ('Sting', 'picar, escocer', 'Verbos irregulares', 'A2'),
  ('Stink', 'apestar, heder', 'Verbos irregulares', 'A2'),
  ('Stride', 'caminar o andar a zancadas', 'Verbos irregulares', 'A2'),
  ('Strike', 'golpear, encender "un cerillo"', 'Verbos irregulares', 'A2'),
  ('Strive', 'esforzarse "en hacer algo"', 'Verbos irregulares', 'A2'),
  ('Swear', 'jurar', 'Verbos irregulares', 'A2'),
  ('Sweat', 'sudar', 'Verbos irregulares', 'A2'),
  ('Sweep', 'barrer', 'Verbos irregulares', 'A2'),
  ('Swell', 'hincharse, inflarse, aumentar de tamaño', 'Verbos irregulares', 'A2'),
  ('Swim', 'nadar', 'Verbos irregulares', 'A2'),
  ('Swing', 'balancear, columpiar', 'Verbos irregulares', 'A2'),
  ('Take', 'tomar "de agarrar", llevar', 'Verbos irregulares', 'A2'),
  ('Teach', 'enseñar "de educar"', 'Verbos irregulares', 'A2'),
  ('Tear', 'rasgar, llorar', 'Verbos irregulares', 'A2'),
  ('Tell', 'decir', 'Verbos irregulares', 'A2'),
  ('Think', 'pensar, creer', 'Verbos irregulares', 'A2'),
  ('Throw', 'tirar, lanzar', 'Verbos irregulares', 'A2'),
  ('Tread on', 'pisar en / sobre', 'Verbos irregulares', 'A2'),
  ('Wake', 'despertar, despertarse', 'Verbos irregulares', 'A2'),
  ('Wear', 'llevar ropa puesta, desgastar, desgastarse', 'Verbos irregulares', 'A2'),
  ('Wed', 'desposar, desposarse', 'Verbos irregulares', 'A2'),
  ('Weep', 'llorar, derramar', 'Verbos irregulares', 'A2'),
  ('Wet', 'humedecer, mojar', 'Verbos irregulares', 'A2'),
  ('Win', 'ganar', 'Verbos irregulares', 'A2'),
  ('Wind', 'enrollar, dar cuerda a', 'Verbos irregulares', 'A2'),
  ('Write', 'escribir', 'Verbos irregulares', 'A2'),
  ('Adjectives and their opposites', 'adjetivos y sus opuestos', 'Verbos irregulares', 'A2'),
  ('Happy', 'feliz', 'Verbos irregulares', 'A2'),
  ('Sad', 'triste', 'Verbos irregulares', 'A2'),
  ('Beautiful', 'hermoso/a', 'Verbos irregulares', 'A2'),
  ('Ugly', 'feo/a', 'Verbos irregulares', 'A2'),
  ('Old', 'viejo/a', 'Verbos irregulares', 'A2'),
  ('Young', 'joven', 'Verbos irregulares', 'A2'),
  ('New', 'nuevo/a', 'Verbos irregulares', 'A2'),
  ('Small', 'chico/a', 'Verbos irregulares', 'A2'),
  ('Large', 'grande, numeroso/a', 'Verbos irregulares', 'A2'),
  ('High', 'alto, elevado/a', 'Verbos irregulares', 'A2'),
  ('Long', 'largo/a', 'Verbos irregulares', 'A2'),
  ('Strong', 'fuerte', 'Verbos irregulares', 'A2'),
  ('Weak', 'débil', 'Verbos irregulares', 'A2'),
  ('Thin', 'delgado/a; flaco/a', 'Verbos irregulares', 'A2'),
  ('Pretty', 'bonita', 'Verbos irregulares', 'A2'),
  ('Handsome', 'apuesto', 'Verbos irregulares', 'A2'),
  ('Front', 'delantero/a, de adelante', 'Verbos irregulares', 'A2'),
  ('Back', 'trasero/a, de atrás', 'Verbos irregulares', 'A2'),
  ('Intelligent', 'inteligente', 'Verbos irregulares', 'A2'),
  ('Stupid', 'estúpido/a', 'Verbos irregulares', 'A2'),
  ('Smart', 'listo/a', 'Verbos irregulares', 'A2'),
  ('Dull', 'torpe', 'Verbos irregulares', 'A2'),
  ('Clever', 'listo/a, abusado/a', 'Verbos irregulares', 'A2'),
  ('Fool', 'tonto/a', 'Verbos irregulares', 'A2'),
  ('Foolish', 'tonto/a; estúpido/a', 'Verbos irregulares', 'A2'),
  ('Silly', 'tonto/a; absurdo/a', 'Verbos irregulares', 'A2'),
  ('Friendly', 'amistoso/a', 'Verbos irregulares', 'A2'),
  ('Unfrienly', 'no amistoso/a', 'Verbos irregulares', 'A2'),
  ('Closed', 'cerrado/a', 'Verbos irregulares', 'A2'),
  ('Dark', 'obscuro/a', 'Verbos irregulares', 'A2'),
  ('Heavy', 'pesado/a', 'Verbos irregulares', 'A2'),
  ('Left', 'izquierdo/a', 'Verbos irregulares', 'A2'),
  ('Right', 'derecho/a', 'Verbos irregulares', 'A2'),
  ('Wrong', 'equivocado/a; incorrecto/a; mal', 'Verbos irregulares', 'A2'),
  ('Famous', 'famoso/a', 'Adjetivos y opuestos', 'A2'),
  ('Unknown', 'desconocido/a', 'Adjetivos y opuestos', 'A2'),
  ('Angry', 'enojado/a', 'Adjetivos y opuestos', 'A2'),
  ('Content', 'contento', 'Adjetivos y opuestos', 'A2'),
  ('Narrow', 'angosto/a; estrecho/a', 'Adjetivos y opuestos', 'A2'),
  ('Wide', 'ancho/a', 'Adjetivos y opuestos', 'A2'),
  ('Absent', 'ausente', 'Adjetivos y opuestos', 'A2'),
  ('Hot', 'caliente', 'Adjetivos y opuestos', 'A2'),
  ('Cold', 'frio/a', 'Adjetivos y opuestos', 'A2'),
  ('Warm', 'tibio/a', 'Adjetivos y opuestos', 'A2'),
  ('Cool', 'fresco/a; genial', 'Adjetivos y opuestos', 'A2'),
  ('Hungry', 'hambriento/a', 'Adjetivos y opuestos', 'A2'),
  ('Satisfied', 'satisfecho/a', 'Adjetivos y opuestos', 'A2'),
  ('Fine', 'excelente, fino/a', 'Adjetivos y opuestos', 'A2'),
  ('Ordinary', 'ordinario/a', 'Adjetivos y opuestos', 'A2'),
  ('Religious', 'religioso/a', 'Adjetivos y opuestos', 'A2'),
  ('Atheistic', 'ateo/a', 'Adjetivos y opuestos', 'A2'),
  ('False', 'falso/a', 'Adjetivos y opuestos', 'A2'),
  ('True', 'verdadero/a', 'Adjetivos y opuestos', 'A2'),
  ('Alike', 'semejante', 'Adjetivos y opuestos', 'A2'),
  ('Different', 'diferente', 'Adjetivos y opuestos', 'A2'),
  ('Similar', 'similar', 'Adjetivos y opuestos', 'A2'),
  ('Elegant', 'elegante', 'Adjetivos y opuestos', 'A2'),
  ('Badly dressed', 'mal vestido/a', 'Adjetivos y opuestos', 'A2'),
  ('Next', 'siguiente; próximo/a', 'Adjetivos y opuestos', 'A2'),
  ('Loose', 'flojo/a; no apretado/a', 'Adjetivos y opuestos', 'A2'),
  ('Tight', 'apretado/a; ajustado/a', 'Adjetivos y opuestos', 'A2'),
  ('Modern', 'moderno/a', 'Adjetivos y opuestos', 'A2'),
  ('Antique', 'antiguo/a', 'Adjetivos y opuestos', 'A2'),
  ('Ancient', 'antiguo/a; ancestral', 'Adjetivos y opuestos', 'A2'),
  ('Wild', 'salvaje, silvestre', 'Adjetivos y opuestos', 'A2'),
  ('Domestic', 'doméstico/a', 'Adjetivos y opuestos', 'A2'),
  ('Fierce', 'fiero/a, feroz', 'Adjetivos y opuestos', 'A2'),
  ('Tame', 'doméstico/a', 'Adjetivos y opuestos', 'A2'),
  ('Sour', 'agrio/a', 'Adjetivos y opuestos', 'A2'),
  ('Sweet', 'dulce', 'Adjetivos y opuestos', 'A2'),
  ('Rich', 'rico/a', 'Adjetivos y opuestos', 'A2'),
  ('Poor', 'pobre', 'Adjetivos y opuestos', 'A2'),
  ('Complete', 'completo/a', 'Adjetivos y opuestos', 'A2'),
  ('Incomplete', 'incompleto/a', 'Adjetivos y opuestos', 'A2'),
  ('Empty', 'vacío/a', 'Adjetivos y opuestos', 'A2'),
  ('Full', 'lleno/a', 'Adjetivos y opuestos', 'A2'),
  ('Hard', 'duro/a; dificil', 'Adjetivos y opuestos', 'A2'),
  ('Soft', 'suave; blando/a', 'Adjetivos y opuestos', 'A2'),
  ('Upward', 'hacia arriba', 'Adjetivos y opuestos', 'A2'),
  ('Downward', 'hacia abajo', 'Adjetivos y opuestos', 'A2'),
  ('Forward', 'hacia delante; delantero/a', 'Adjetivos y opuestos', 'A2'),
  ('Cheap', 'barato/a', 'Adjetivos y opuestos', 'A2'),
  ('Expensive', 'caro/a; costoso/a', 'Adjetivos y opuestos', 'A2'),
  ('Deep', 'profundo/a', 'Adjetivos y opuestos', 'A2'),
  ('Shallow', 'poco profundo/a; superficial', 'Adjetivos y opuestos', 'A2'),
  ('Joyful', 'alegre', 'Adjetivos y opuestos', 'A2'),
  ('Sorrowful', 'afligido', 'Adjetivos y opuestos', 'A2'),
  ('Good', 'bueno/a', 'Adjetivos y opuestos', 'A2'),
  ('Bad', 'malo/a', 'Adjetivos y opuestos', 'A2'),
  ('Preposiciones I *appendix 3* Prepositions', 'preposiciones', 'Preposiciones', 'A2'),
  ('Direction', 'dirección', 'Preposiciones', 'A2'),
  ('Location', 'localización', 'Preposiciones', 'A2'),
  ('Position', 'posición', 'Preposiciones', 'A2'),
  ('The place of origen', 'el lugar de origen', 'Preposiciones', 'A2'),
  ('The place of destination', 'el lugar de destino', 'Preposiciones', 'A2'),
  ('Size', 'medida, tamaño', 'Preposiciones', 'A2'),
  ('Time', 'hora, tiempo', 'Preposiciones', 'A2'),
  ('Next to', 'junto a', 'Preposiciones', 'A2'),
  ('Beside', 'junto a; al lado de', 'Preposiciones', 'A2'),
  ('Near', 'cerca de', 'Preposiciones', 'A2'),
  ('Far from', 'lejos de', 'Preposiciones', 'A2'),
  ('My house is near your house', 'mi casa es cerca de tu casa', 'Preposiciones', 'A2'),
  ('Our chairs are close to the blackboard', 'nuestras sillas están cerca de el pizarrón', 'Preposiciones', 'A2'),
  ('My town is far from your city', 'mi pueblo esta lejos de tu ciudad', 'Preposiciones', 'A2'),
  ('Opposite', 'opuesto a, en frente de, frente a', 'Preposiciones', 'A2'),
  ('In front of', 'en frente de', 'Preposiciones', 'A2'),
  ('Behind', 'detrás de, atrás de', 'Preposiciones', 'A2'),
  ('In back of', 'atrás de, detrás de', 'Preposiciones', 'A2'),
  ('In the front of', 'en la parte delantera de', 'Preposiciones', 'A2'),
  ('In the back of', 'en la parte trasera de', 'Preposiciones', 'A2'),
  ('At the back', 'en la parte de atrás', 'Preposiciones', 'A2'),
  ('The garden is behind the house', 'el jardín esta atrás de la casa', 'Preposiciones', 'A2'),
  ('The big chair is at the back', 'la silla grande esta en la parte de atrás', 'Preposiciones', 'A2'),
  ('Down', 'abajo', 'Preposiciones', 'A2'),
  ('Of', 'de "indicando posesión"', 'Preposiciones', 'A2'),
  ('From', 'de o desde "indicando procedencia"', 'Preposiciones', 'A2'),
  ('Into', 'en o hacia el interior de "indica el movimiento de algo o alguien hacia una superficie interior"', 'Preposiciones', 'A2'),
  ('Onto', 'en o sore "indica el movimiento de algo o alguien hacia una superficie exterior"', 'Preposiciones', 'A2'),
  ('Your things are down here', 'tus cosas están aquí abajo', 'Preposiciones', 'A2'),
  ('There are clothes inside that drawer', 'hay ropa dentro de ese cajón', 'Preposiciones', 'A2'),
  ('My dog is outside the house', 'mi perro esta afuera de la casa', 'Preposiciones', 'A2'),
  ('We are out of salt', 'nosotros estamos sin sal', 'Preposiciones', 'A2'),
  ('It is made out of plastic', 'esta hecho de plástico', 'Preposiciones', 'A2'),
  ('I want a kilogram of sugar', 'yo quiero un kilogramo de azúcar', 'Preposiciones', 'A2'),
  ('She is from Mexico', 'ella es de México', 'Preposiciones', 'A2'),
  ('He puts his socks into the drawer', 'él pone sus calcetines en el cajón', 'Preposiciones', 'A2'),
  ('He jumps onto the back of his truck', 'el salta en la parte trasera de su camioneta', 'Preposiciones', 'A2'),
  ('By', 'por, por medio de', 'Preposiciones', 'A2'),
  ('She is sick by a virus', 'ella esta enferma por un virus', 'Preposiciones', 'A2'),
  ('Side by side', 'lado por lado', 'Preposiciones', 'A2'),
  ('One by one', 'uno por uno', 'Preposiciones', 'A2'),
  ('By sight', 'de vista, por vista', 'Preposiciones', 'A2'),
  ('By mistake', 'por error', 'Preposiciones', 'A2'),
  ('By the way', 'por cierto', 'Preposiciones', 'A2'),
  ('By way of', 'por medio de, por la vía de, por el camino de', 'Preposiciones', 'A2'),
  ('By far', 'en mucho, por mucho, sin duda', 'Preposiciones', 'A2'),
  ('With', 'con', 'Preposiciones', 'A2'),
  ('During', 'durante', 'Preposiciones', 'A2'),
  ('Between', 'entre dos cosas, personas o animales', 'Preposiciones', 'A2'),
  ('Among', 'entre tres o más cosas, personas o animales', 'Preposiciones', 'A2'),
  ('Almost', 'casi', 'Preposiciones', 'A2'),
  ('She does a very good work without help', 'ella hace un muy buen trabajo sin ayuda', 'Preposiciones', 'A2'),
  ('He eats during all the afternoon', 'él come durante toda la tarde', 'Preposiciones', 'A2'),
  ('The nose is between the eyes', 'la nariz esta entre los ojos', 'Preposiciones', 'A2'),
  ('You are almost finishing this course', 'tu estas casi terminando este curso', 'Preposiciones', 'A2'),
  ('Spring is after winter', 'la primavera es después del invierno', 'Preposiciones', 'A2'),
  ('The love is before your eyes', 'el amor esta frente a tus ojos', 'Preposiciones', 'A2'),
  ('Winter is before spring', 'el invierno es antes de la primavera', 'Preposiciones', 'A2'),
  ('Go after my dog!, It runs very fast', 've tras o detrás de mi perro, corre muy rápido', 'Preposiciones', 'A2'),
  ('What is this subject about?', 'acerca de que es este tema?', 'Preposiciones', 'A2'),
  ('My dog is running about this place', 'mi perro esta corriendo por todas partes de este lugar', 'Preposiciones', 'A2'),
  ('Please, take your things to your room', 'por favor, lleva tus cosas a tu cuarto', 'Preposiciones', 'A2'),
  ('For', 'por, para', 'Preposiciones', 'A2'),
  ('I am going to the restaurant for lunch', 'yo voy al restaurante para almorzar', 'Preposiciones', 'A2'),
  ('He is studying for an exam', 'el esta estudiando para un examen', 'Preposiciones', 'A2'),
  ('It rains for days during winters', 'llueve por días durante los inviernos', 'Preposiciones', 'A2'),
  ('Wait for me to come out', 'espera por mi salir = espera que yo salga', 'Preposiciones', 'A2'),
  ('Since', 'desde', 'Preposiciones', 'A2'),
  ('Ever since', 'desde o desde entonces', 'Preposiciones', 'A2'),
  ('I am sick since 2 weeks ago', 'yo estoy enfermo desde hace dos semanas', 'Preposiciones', 'A2'),
  ('I am married and happy ever since', 'yo estoy casado y feliz desde entonces', 'Preposiciones', 'A2'),
  ('Toward', 'hacia, en dirección de/a', 'Preposiciones', 'A2'),
  ('Through', 'por; a través de; durante "cuando se refiere al "tiempo cronológico"', 'Preposiciones', 'A2'),
  ('Throughout', 'por todas partes de "hablando de lugar" ; durante todo "hablado de tiempo cronológico"', 'Preposiciones', 'A2'),
  ('As far as', 'tan lejos como; hasta "refiriéndose a distancia"', 'Preposiciones', 'A2'),
  ('Top', 'hasta arriba, lo mas alto, lo máximo, la cima', 'Preposiciones', 'A2'),
  ('On top of', 'encima de, en la cima de', 'Preposiciones', 'A2'),
  ('Above', 'por encima de', 'Preposiciones', 'A2'),
  ('Over', 'sobre; encima de; aproximadamente o alrededor de "hablando de cantidad"; concluido', 'Preposiciones', 'A2'),
  ('Under', 'debajo de, debajo de', 'Preposiciones', 'A2'),
  ('Below', 'por debajo de', 'Preposiciones', 'A2'),
  ('At the bottom', 'en lo mas bajo de', 'Preposiciones', 'A2'),
  ('To the bottom', 'hasta el fondo', 'Preposiciones', 'A2'),
  ('Upon', 'sobre', 'Preposiciones', 'A2'),
  ('A bullet can pass through my body', 'una bala puede pasar a través de mi cuerpo', 'Preposiciones', 'A2'),
  ('I am going to wait through 5 hours', 'yo voy a esperar durante 5 horas', 'Preposiciones', 'A2'),
  ('She eats throughout the hours of the day', 'ella come durante todas las horas del día', 'Preposiciones', 'A2'),
  ('The sky is above the clouds', 'el cielo es por encima de las nubes', 'Preposiciones', 'A2'),
  ('We fly over the houses', 'nosotros volamos encima de las casas', 'Preposiciones', 'A2'),
  ('This book is on industrial engineering', 'este libro es de o sobre ingeniería industrial', 'Preposiciones', 'A2'),
  ('Is the list under the book?', 'esta la lista debajo de el libro?', 'Preposiciones', 'A2'),
  ('I am under stress', 'yo estoy bajo stress', 'Preposiciones', 'A2'),
  ('She isnot swimming below her life belt', 'ella no esta nadando por debajo de su salvavidas', 'Preposiciones', 'A2'),
  ('I am to the bottom on this', 'yo estoy hasta el fondo en esto', 'Preposiciones', 'A2'),
  ('Let´s drink to the bottom!', 'bebamos hasta el fondo!', 'Preposiciones', 'A2'),
  ('My pet is on the sofa', 'mi mascota esta en/sobre el sofa', 'Preposiciones', 'A2'),
  ('Today is my day off', 'hoy es mi día libre', 'Preposiciones', 'A2'),
  ('My friends are off their houses', 'mis amigos están fuera de sus casas', 'Preposiciones', 'A2'),
  ('Around', 'alrededor de, a la vuelta de', 'Preposiciones', 'A2'),
  ('Along', 'a lo largo de', 'Preposiciones', 'A2'),
  ('All along', 'a todo lo largo, a lo largo de todo', 'Preposiciones', 'A2'),
  ('Along with', 'a lo largo con o junto con', 'Preposiciones', 'A2'),
  ('Alongside', 'al lado de "en sentido de movimiento junto a alguien o a algo"', 'Preposiciones', 'A2'),
  ('Across', 'del otro lado de "implica movimiento de un lado a otro sin atravesar', 'Preposiciones', 'A2'),
  ('Beyond', 'tras, mas allá de', 'Preposiciones', 'A2'),
  ('Put your arms against the wall', 'pon tus brazos contra la pared', 'Preposiciones', 'A2'),
  ('Please, go around the park', 'por favor, ve alrededor del parque', 'Preposiciones', 'A2'),
  ('The shop is around the corner', 'la tienda esta a la vuelta de la esquina', 'Preposiciones', 'A2'),
  ('I walk along this street every day', 'yo camino a largo de esta calle cada día', 'Preposiciones', 'A2'),
  ('The plane is flying alongside a jet', 'el avión esta volando al lado de un jet', 'Preposiciones', 'A2'),
  ('The bus goes past this city without stopping', 'el autobús va por o más allá de esta ciudad sin parar', 'Preposiciones', 'A2'),
  ('Possessive adjectives and pronouns', 'adjetivos y pronombres posesivos', 'Pronombres posesivos', 'A2'),
  ('Mine', 'mio / a', 'Pronombres posesivos', 'A2'),
  ('Yours', 'tuyo / a', 'Pronombres posesivos', 'A2'),
  ('His', 'suyo "de él"', 'Pronombres posesivos', 'A2'),
  ('Hers', 'suyo "de ella"', 'Pronombres posesivos', 'A2'),
  ('Ours', 'de nosotros', 'Pronombres posesivos', 'A2'),
  ('Theirs', 'de ellos', 'Pronombres posesivos', 'A2'),
  ('My house', 'mi casa', 'Pronombres posesivos', 'A2'),
  ('Your fruits', 'tus frutas', 'Pronombres posesivos', 'A2'),
  ('His pencil', 'su lápiz "de el"', 'Pronombres posesivos', 'A2'),
  ('Her mirrow', 'su espejo "de ella"', 'Pronombres posesivos', 'A2'),
  ('Otros ejemplos en affirmative', 'afirmativo', 'Pronombres posesivos', 'A2'),
  ('Their names are beautiful = they are beautiful', 'sus nombres son hermosos', 'Pronombres posesivos', 'A2'),
  ('His book is interesting = it is interesting', 'su libro es interesante', 'Pronombres posesivos', 'A2'),
  ('Pronombres demostrativos Demonstrative pronouns', 'pronombres demostrativos', 'Pronombres demostrativos', 'A2'),
  ('This', 'esto, a', 'Pronombres demostrativos', 'A2'),
  ('That', 'eso, a; aquello, a', 'Pronombres demostrativos', 'A2'),
  ('These', 'estos, as', 'Pronombres demostrativos', 'A2'),
  ('Those', 'esos, as; aquellos, as', 'Pronombres demostrativos', 'A2'),
  ('There is and there are There is', 'hay', 'Pronombres demostrativos', 'A2'),
  ('There is going to be', 'va a haber', 'Pronombres demostrativos', 'A2'),
  ('There are going to be', 'va a haber', 'Pronombres demostrativos', 'A2'),
  ('On april the seventh', 'en el séptimo día de abril', 'Pronombres posesivos', 'A2'),
  ('On holidays', 'en vacaciones', 'Pronombres posesivos', 'A2'),
  ('A book on physics', 'a buk on fisics', 'Pronombres posesivos', 'A2'),
  ('On the train', 'en el tren', 'Pronombres posesivos', 'A2'),
  ('To be on vacations', 'estar de o en vacaciones', 'Pronombres posesivos', 'A2'),
  ('On the plane', 'en el avión', 'Pronombres posesivos', 'A2'),
  ('On the telephone', 'en el teléfono', 'Pronombres posesivos', 'A2'),
  ('On the cinema', 'en el cinema', 'Pronombres posesivos', 'A2'),
  ('They live in a city', 'ellos viven en una ciudad', 'Pronombres posesivos', 'A2'),
  ('His mother is in that house', 'su madre esta en esa casa', 'Pronombres posesivos', 'A2'),
  ('My things are in my room', 'mis cosas están en mi cuarto', 'Pronombres posesivos', 'A2'),
  ('They are at home', 'ellos están en casa', 'Pronombres posesivos', 'A2'),
  ('He is at work', 'el esta en el trabajo', 'Pronombres posesivos', 'A2'),
  ('She is at the door', 'ella esta en la puerta', 'Pronombres posesivos', 'A2'),
  ('At midnight', 'a media noche', 'Pronombres posesivos', 'A2'),
  ('At night', 'en la noche', 'Pronombres posesivos', 'A2'),
  ('Arrive at', 'llegar a', 'Pronombres posesivos', 'A2'),
  ('Reading', 'leyendo', 'Uso del -ing', 'A2'),
  ('I like', 'jugando el juego que me gusta', 'Uso del -ing', 'A2'),
  ('I want another new shirt', 'yo quiero una camisa nueva', 'Uso del -ing', 'A2'),
  ('Are the other fruits in their box?', 'están las otras frutas en su caja?', 'Uso del -ing', 'A2'),
  ('The other pants are in the drawers', 'los otros pantalones están en los cajones', 'Uso del -ing', 'A2'),
  ('These shoes are mine, the others are yours', 'estos zapatos son míos, los otros son tuyos', 'Uso del -ing', 'A2'),
  ('Presente simple Simple present', 'presente simple', 'Presente simple', 'A2'),
  ('She has a nice friend', 'ella tiene un amigo agradable', 'Presente simple', 'A2'),
  ('It takes time to know a person', 'toma tiempo conocer una persona', 'Presente simple', 'A2'),
  ('She doesn´t love her boyfriend', 'ella no ama a su novio', 'Presente simple', 'A2'),
  ('Do we have to sleep early every day?', '¿tenemos nosotros que dormir temprano cada día?', 'Presente simple', 'A2'),
  ('Does she have beautiful legs?', '¿tiene ella piernas hermosas?', 'Presente simple', 'A2'),
  ('Does your mother love the life?', '¿ama tu mama la vida?', 'Presente simple', 'A2'),
  ('Palabras interrogativas Question words', 'palabras interrogativas', 'Palabras interrogativas', 'A2'),
  ('What is that?', '¿que es eso?', 'Palabras interrogativas', 'A2'),
  ('What are you doing?', 'que estas tu haciendo?', 'Palabras interrogativas', 'A2'),
  ('What time is it?', 'que hora es?', 'Palabras interrogativas', 'A2'),
  ('What are you thinking about those persons?', 'que estas pensando acerca de esas personas?', 'Palabras interrogativas', 'A2'),
  ('Which house is yours?', '¿cual casa es tuya?', 'Palabras interrogativas', 'A2'),
  ('Which one is your name?', '¿cuál es tu nombre?', 'Palabras interrogativas', 'A2'),
  ('How is the exam going to be?', '¿cómo va a ser el examen?', 'Palabras interrogativas', 'A2'),
  ('How tall are you?', '¿que tan alto eres tu?', 'Palabras interrogativas', 'A2'),
  ('You cannot see how pretty she is!', '¡tu no puedes ver que tan bonita es ella!', 'Palabras interrogativas', 'A2'),
  ('How about going to eat?', '¿que te parece ir a comer?', 'Palabras interrogativas', 'A2'),
  ('How come!', 'de que manera!, Como es que!', 'Palabras interrogativas', 'A2'),
  ('Who is that?', '¿Quién es ese o esa?', 'Palabras interrogativas', 'A2'),
  ('Who is it?', '¿quien es?', 'Palabras interrogativas', 'A2'),
  ('Who are you looking for?', '¿A quién esta usted buscando?', 'Palabras interrogativas', 'A2'),
  ('The man who is there is tall', 'el hombre que esta allá es alto', 'Palabras interrogativas', 'A2'),
  ('Where is your hat', '¿donde esta tu sombrero?', 'Palabras interrogativas', 'A2'),
  ('Where is that city?', '¿dónde esta esa ciudad?', 'Palabras interrogativas', 'A2'),
  ('When are you going to do your homework?', '¿cuándo vas tu a hacer tu tarea?', 'Palabras interrogativas', 'A2'),
  ('When is it going to happen?', '¿cuándo va a pasar?', 'Palabras interrogativas', 'A2'),
  ('Why is he doing this to your brother?', '¿por que esta el haciendo eso a tu hermano?', 'Palabras interrogativas', 'A2'),
  ('Why are you here?', '¿por que estas tu aquí?', 'Palabras interrogativas', 'A2'),
  ('What are you here for?', '¿para que estas tu aquí?', 'Palabras interrogativas', 'A2'),
  ('What are you studying for?', 'para que estas tu estudiando?', 'Palabras interrogativas', 'A2'),
  ('That´s the reason why he is rich', 'esa es la razón por la que él es rico', 'Palabras interrogativas', 'A2'),
  ('Because she wants to', 'why', 'Palabras interrogativas', 'A2'),
  ('Are you?', 'Verdad?', 'Palabras interrogativas', 'A2'),
  ('Neither you nor I am going there', 'ni tú ni yo vamos a ir allá', 'Palabras interrogativas', 'A2'),
  ('Neither of you', 'ninguno de ustedes', 'Palabras interrogativas', 'A2'),
  ('Either or you', 'cualquiera de ustedes', 'Palabras interrogativas', 'A2'),
  ('Hardly', 'difícilmente', 'Palabras interrogativas', 'A2'),
  ('Barely', 'apenas', 'Palabras interrogativas', 'A2'),
  ('As far as I am concerned', 'tan lejos como a mí me concierne o en lo que a mí concierne', 'Palabras interrogativas', 'A2'),
  ('Right away', 'de inmediato, inmediatamente', 'Palabras interrogativas', 'A2'),
  ('On the whole', 'en general', 'Palabras interrogativas', 'A2'),
  ('That has something to do with my case', 'eso tiene algo que ver con mi caso', 'Palabras interrogativas', 'A2'),
  ('Always', 'siempre', 'Adverbios de frecuencia', 'B1'),
  ('Usually', 'usualmente', 'Adverbios de frecuencia', 'B1'),
  ('Often', 'a menudo', 'Adverbios de frecuencia', 'B1'),
  ('Frequently', 'frecuentemente', 'Adverbios de frecuencia', 'B1'),
  ('Sometimes', 'algunas veces, a veces', 'Adverbios de frecuencia', 'B1'),
  ('How often...?', 'que tan seguido o con que frecuencia...?', 'Adverbios de frecuencia', 'B1'),
  ('Seldom', 'casi nunca', 'Adverbios de frecuencia', 'B1'),
  ('Rarely', 'rara vez', 'Adverbios de frecuencia', 'B1'),
  ('Never', 'nunca', 'Adverbios de frecuencia', 'B1'),
  ('Examples', 'ejemplos', 'Adverbios de frecuencia', 'B1'),
  ('I usually kiss my girlfriend', 'yo usualmente beso a mi novia', 'Adverbios de frecuencia', 'B1'),
  ('He is always worry about the exams', 'el esta siempre preocupado acerca / de los exámenes', 'Adverbios de frecuencia', 'B1'),
  ('Are they often doing their homework?', 'están ellos a menudo haciendo su tarea?', 'Adverbios de frecuencia', 'B1'),
  ('She rarely works on sunday', 'ella raramente trabaja en domingo', 'Adverbios de frecuencia', 'B1'),
  ('We are seldom dreaming on going to europe', 'nosotros rara vez estamos soñando en ir a Europa', 'Adverbios de frecuencia', 'B1'),
  ('You never listen to me', 'tu nunca me escuchas', 'Adverbios de frecuencia', 'B1'),
  ('Does she always study at nights?', 'estudia ella siempre en / por las noches?', 'Adverbios de frecuencia', 'B1'),
  ('Is he usually at home?', 'esta el usualmente en casa?', 'Adverbios de frecuencia', 'B1'),
  ('Are you sometimes going to my house?', 'estas tu a veces yendo a mi casa?', 'Adverbios de frecuencia', 'B1'),
  ('R = no, she never does it', 'estudia ella alguna vez sus lecciones de inglés?', 'Adverbios de frecuencia', 'B1'),
  ('They are working more than ever!', 'ellos están trabajando mas que nunca!', 'Adverbios de frecuencia', 'B1'),
  ('Comparativos Comparatives', 'comparativos', 'Comparativos', 'B1'),
  ('Delicious', 'delicioso', 'Comparativos', 'B1'),
  ('He is less intelligent than your other friend', 'el es menos inteligente que tu otro amigo', 'Comparativos', 'B1'),
  ('He is good playing piano', 'el es bueno tocando piano', 'Comparativos', 'B1'),
  ('I am bad doing that', 'yo soy malo haciendo eso', 'Comparativos', 'B1'),
  ('He is bad learning english', 'él es malo aprendiendo inglés', 'Comparativos', 'B1'),
  ('We are bad at tennis', 'nosotros somos malos en el tenis', 'Comparativos', 'B1'),
  ('Well', 'bien', 'Comparativos', 'B1'),
  ('She plays the piano well', 'ella toca el piano bien', 'Comparativos', 'B1'),
  ('You hit the ball badly', 'tu le pegas a la pelota mal', 'Comparativos', 'B1'),
  ('She always does her homework badly', 'el siempre hace su tarea mal', 'Comparativos', 'B1'),
  ('Good / well...better', 'mejor', 'Comparativos', 'B1'),
  ('Far', 'lejos', 'Comparativos', 'B1'),
  ('Little', 'poco / a', 'Comparativos', 'B1'),
  ('Much', 'mucho/a', 'Comparativos', 'B1'),
  ('Few', 'pocos / as', 'Comparativos', 'B1'),
  ('Do as I do', 'has como yo hago', 'Comparativos', 'B1'),
  ('As he says', 'como ella dice', 'Comparativos', 'B1'),
  ('He works as a lawyer', 'él trabaja como un abogado', 'Comparativos', 'B1'),
  ('Give that camara as a present', 'da esa camara como un regalo', 'Comparativos', 'B1'),
  ('As for me, I don´t go with you', 'en cuanto a mí, yo no voy contigo', 'Comparativos', 'B1'),
  ('As well as', 'así como también, además de', 'Comparativos', 'B1'),
  ('Such as', 'tal como, tales como, así como', 'Comparativos', 'B1'),
  ('Jessica is as rich as her friend Tomy', 'Jessica es tan rica como su amigo Tomy', 'Comparativos', 'B1'),
  ('He is not french but american', 'el no es francés sino americano', 'Comparativos', 'B1'),
  ('You can go there by taking a bus', 'tú puedes ir allá por medio de tomar un autobús', 'Comparativos', 'B1'),
  ('By the way!', 'a propósito!', 'Comparativos', 'B1'),
  ('To pay by check', 'pagar con cheque', 'Comparativos', 'B1'),
  ('I always take my girl by the hand', 'yo siempre tomo a mi chica por/de la mano', 'Comparativos', 'B1'),
  ('By candlelight', 'a la luz de las velas', 'Comparativos', 'B1'),
  ('This is caused by my mind', 'esto es causado por mi mente', 'Comparativos', 'B1'),
  ('If so', 'si es así. . .; De ser así', 'Comparativos', 'B1'),
  ('I think so', 'pienso o creo que si, lo pienso así', 'Comparativos', 'B1'),
  ('So far', 'hasta ahora, por ahora', 'Comparativos', 'B1'),
  ('So far so good', 'hasta ahora todo va bien', 'Comparativos', 'B1'),
  ('I hope so', 'espero que si', 'Comparativos', 'B1'),
  ('Superlativos Superlatives', 'superlativos', 'Superlativos', 'B1'),
  ('Para good / well = the best', 'el mejor', 'Superlativos', 'B1'),
  ('Para bad / badly = the worst', 'el peor', 'Superlativos', 'B1'),
  ('Para far = the farthest', 'el mas lejos o lejano', 'Superlativos', 'B1'),
  ('Para little = the least', 'el menos, el mas poco, lo mas poco, el menor, menos', 'Superlativos', 'B1'),
  ('Para few = the fewest', 'los/las mas pocos/as, los/las menos, menos', 'Superlativos', 'B1'),
  ('Much / many = the most', 'el mas, la mas, los mas, las mas, la mayoría', 'Superlativos', 'B1'),
  ('He is the worst playing football', 'él es el peor jugando fútbol', 'Superlativos', 'B1'),
  ('What town is the farthest from here?', 'que pueblo esta lo mas lejos de aquí?', 'Superlativos', 'B1'),
  ('Who do you love least?', '¿a quién amas menos?', 'Superlativos', 'B1'),
  ('It´s the least he can do', 'es lo menos que el puede hacer', 'Superlativos', 'B1'),
  ('Who do you love most in this life?', '¿a quien amas mas en esta vida?', 'Superlativos', 'B1'),
  ('Most people like to live very well', 'la mayoría de la gente le gusta vivir muy bien', 'Superlativos', 'B1'),
  ('Pronombres reflexivos Reflexive pronouns', 'pronombres reflexivos', 'Pronombres', 'B1'),
  ('Yourself', 'tu mismo', 'Pronombres', 'B1'),
  ('Himself', 'el mismo', 'Pronombres', 'B1'),
  ('Herself', 'ella misma', 'Pronombres', 'B1'),
  ('Itself', 'sí mismo "refiriéndose a una cosa o un animal', 'Pronombres', 'B1'),
  ('Ourselves', 'nosotros mismos', 'Pronombres', 'B1'),
  ('Yourselves', 'ustedes mismos', 'Pronombres', 'B1'),
  ('Themselves', 'ellos mismos', 'Pronombres', 'B1'),
  ('Pronombres del predicado Object pronouns', 'pronombres del predicado', 'Pronombres', 'B1'),
  ('I love me', 'a mí', 'Pronombres', 'B1'),
  ('She gives him a kiss', 'ella da a el un beso = ella le da un beso a él = ella lo besa', 'Pronombres', 'B1'),
  ('Please, don´t hit me', 'por favor, no me pegue', 'Pronombres', 'B1'),
  ('This secret is only between you and me', 'este secreto es solo entre tú y yo', 'Pronombres', 'B1'),
  ('He loves her with all his heart', 'él ama a ella con todo su corazón', 'Pronombres', 'B1'),
  ('I am going to dance with her', 'yo voy a bailar con ella', 'Pronombres', 'B1'),
  ('I am doing this for you', 'yo estoy haciendo esto por ti', 'Pronombres', 'B1'),
  ('What about her?', 'que acerca de ella?', 'Pronombres', 'B1'),
  ('I don´t want to sleep on it', 'yo no quiero dormir en / sobre eso', 'Pronombres', 'B1'),
  ('Go after them!', 've tras ellos!', 'Pronombres', 'B1'),
  ('All of you', 'todo de "ustedes" = todos ustedes', 'Pronombres', 'B1'),
  ('All of us', 'todo de "nosotros" = todos nosotros', 'Pronombres', 'B1'),
  ('Both of them', 'ambos de "ellos" = a ambos "de ustedes"', 'Pronombres', 'B1'),
  ('The 2 of you', 'los dos de "ustedes" = ustedes dos', 'Pronombres', 'B1'),
  ('I want her to come with me', 'yo quiero que ella venga conmigo', 'Pronombres', 'B1'),
  ('I insist on her coming early', 'yo insisto en su llegada "de ella" temprano', 'Pronombres', 'B1'),
  ('This is for you to keep it', 'esto es para que tú lo conserves', 'Pronombres', 'B1'),
  ('Please, make her cry for me', 'por favor, hazla llorar por mí', 'Pronombres', 'B1'),
  ('I see her go every saturday', 'yo la veo irse cada sábado', 'Pronombres', 'B1'),
  ('They hear me shout when I cry', 'ellos me escuchan gritar cuando yo lloro', 'Pronombres', 'B1'),
  ('Betsi is to go on vacation this summer', 'betsi ira de vacaciones este verano', 'Pronombres', 'B1'),
  ('He is to have a lot of money', 'el tendra un montón de dinero', 'Pronombres', 'B1'),
  ('Depend on', 'depende de', 'Pronombres', 'B1'),
  ('Smile at', 'sonrreir a', 'Pronombres', 'B1'),
  ('Worry about', 'preocuparse de', 'Pronombres', 'B1'),
  ('Cuantificadores Quantifiers', 'cuantificadores', 'Cuantificadores', 'B1'),
  ('Bicycle', 'bicicleta', 'Cuantificadores', 'B1'),
  ('Milk', 'leche', 'Cuantificadores', 'B1'),
  ('Water', 'agua', 'Cuantificadores', 'B1'),
  ('Mole', 'mole', 'Cuantificadores', 'B1'),
  ('Coffe', 'café', 'Cuantificadores', 'B1'),
  ('Tea', 'te', 'Cuantificadores', 'B1'),
  ('Chocolate', 'chocolate', 'Cuantificadores', 'B1'),
  ('Salt', 'sal', 'Cuantificadores', 'B1'),
  ('Money', 'dinero', 'Cuantificadores', 'B1'),
  ('Sunshine', 'luz o brillo del sol', 'Cuantificadores', 'B1'),
  ('Butter', 'mantequilla', 'Cuantificadores', 'B1'),
  ('Liquor', 'licor', 'Cuantificadores', 'B1'),
  ('Sugar', 'azúcar', 'Cuantificadores', 'B1'),
  ('Mayonnaise', 'mayonesa', 'Cuantificadores', 'B1'),
  ('Seafood', 'mariscos', 'Cuantificadores', 'B1'),
  ('A bottle of liquor', 'una botella de licor', 'Cuantificadores', 'B1'),
  ('A can of seafood', 'una lata de mariscos', 'Cuantificadores', 'B1'),
  ('A jar of beer', 'un tarro de cerveza', 'Cuantificadores', 'B1'),
  ('A pack of cigarettes', 'un paquete de cigarros', 'Cuantificadores', 'B1'),
  ('A box of', 'una caja de', 'Cuantificadores', 'B1'),
  ('A bunch of', 'un grupo, manojo, racimo o bonche de', 'Cuantificadores', 'B1'),
  ('I have some books', 'yo tengo algunos libros', 'Cuantificadores', 'B1'),
  ('Do you have some sugar in that glass?', '¿tienes algo de azúcar en ese vaso?', 'Cuantificadores', 'B1'),
  ('Are there some hotels over there?', '¿hay algunos hoteles por allá?', 'Cuantificadores', 'B1'),
  ('Any', 'algun, alguno/a, algunos /as, algo de, ningún, ninguno/a, ningunos/as', 'Cuantificadores', 'B1'),
  ('You don´t need any problems today', 'tu no necesitas ningunos problemas hoy', 'Cuantificadores', 'B1'),
  ('Does she have any children?', '¿tiene ella algunos niños?', 'Cuantificadores', 'B1'),
  ('I don´t have any money', 'yo no tengo ningún dinero', 'Cuantificadores', 'B1'),
  ('Any teacher can tell you that', 'cualquier profesor puede decirte eso', 'Cuantificadores', 'B1'),
  ('You can die in any moment', 'tu puedes morir en cualquier momento', 'Cuantificadores', 'B1'),
  ('Any of us', 'cualquiera de nosotros', 'Cuantificadores', 'B1'),
  ('Any of you', 'cualquiera de ustedes', 'Cuantificadores', 'B1'),
  ('Any of them', 'cualquiera de ellos', 'Cuantificadores', 'B1'),
  ('Much luck', 'mucha suerte', 'Cuantificadores', 'B1'),
  ('Much problem', 'mucho problema', 'Cuantificadores', 'B1'),
  ('A little rain', 'un poco de lluvia', 'Cuantificadores', 'B1'),
  ('A little money', 'un poco de dinero', 'Cuantificadores', 'B1'),
  ('Little thing', 'poca cosa', 'Cuantificadores', 'B1'),
  ('Little sugar', 'poca azúcar', 'Cuantificadores', 'B1'),
  ('The little girl', 'la niña pequeña', 'Cuantificadores', 'B1'),
  ('The little cars', 'los carros pequeños', 'Cuantificadores', 'B1'),
  ('He speaks very little french', 'él habla mucho poco francés', 'Cuantificadores', 'B1'),
  ('Many things are difficult this days', 'muchas cosas son difíciles estos días', 'Cuantificadores', 'B1'),
  ('A few things', 'unas pocas cosas, algunas cosas', 'Cuantificadores', 'B1'),
  ('A few apples', 'unas cuantas manzanas', 'Cuantificadores', 'B1'),
  ('All night long', 'a lo largo de toda la noche o toda la noche', 'Cuantificadores', 'B1'),
  ('This skirt is as long as your sister´s', 'esta falda es tan larga como la de tu hermana', 'Cuantificadores', 'B1'),
  ('It´s just that', 'es solo que', 'Cuantificadores', 'B1'),
  ('He is just tired', 'se acaba de cansar', 'Cuantificadores', 'B1'),
  ('Calificadores Qualifiers', 'calificadores', 'Cuantificadores', 'B1'),
  ('You have a pretty nice car', 'tú tienes un muy bonito auto', 'Cuantificadores', 'B1'),
  ('My new shirt is pretty warm', 'mi camisa nueva es muy tibia', 'Cuantificadores', 'B1'),
  ('It is rather late', 'es bastante/muy tarde', 'Cuantificadores', 'B1'),
  ('I am able to do it', 'yo puedo hacerlo', 'Cuantificadores', 'B1'),
  ('He can´t open the door', 'el no puede abrir la puerta', 'Cuantificadores', 'B1'),
  ('Can she speak english as you do it?', '¿puede ella hablar inglés como tu lo haces?', 'Cuantificadores', 'B1'),
  ('He may kiss her this evening', 'él puede "posiblemente" besarla esta noche', 'Cuantificadores', 'B1'),
  ('May I dance with you?', '¿puedo bailar contigo? "permiso"', 'Cuantificadores', 'B1'),
  ('May I have a glass of water?', '¿puedo tener un baso de agua? "en el sentido de que nos lo den"', 'Cuantificadores', 'B1'),
  ('He must do it tonight', 'el debe hacerlo esta noche', 'Cuantificadores', 'B1'),
  ('I must be able to do this', 'yo debo poder hacer esto', 'Cuantificadores', 'B1'),
  ('They may be here tomorrow', 'ellos pueden "posiblemente" estar aquí mañana', 'Cuantificadores', 'B1'),
  ('She shouldn´t kill animals', 'ella no bebería matar animales', 'Cuantificadores', 'B1'),
  ('Should I see a doctor every month?', '¿debería yo ver a un doctor cada mes?', 'Cuantificadores', 'B1'),
  ('Should I go with them?', '¿debería yo ir con ellos?', 'Cuantificadores', 'B1'),
  ('This ought to be easy', 'esto debiera ser fácil', 'Cuantificadores', 'B1'),
  ('The winners ought to be them', 'los ganadores debieran ser ellos', 'Cuantificadores', 'B1'),
  ('I ought not to be here', 'yo no debiera estar aquí', 'Cuantificadores', 'B1'),
  ('It will eat its food if it wants', 'comerá su comida si quiere', 'Cuantificadores', 'B1'),
  ('She won´t want to do it', 'ella no querrá hacerlo', 'Futuro y pasado', 'B1'),
  ('Do time', 'hacer tiempo', 'Do and make', 'B1'),
  ('Do a service', 'hacer un servicio', 'Do and make', 'B1'),
  ('Do the homework', 'hacer la tarea', 'Do and make', 'B1'),
  ('Do the dishes', 'limpiar los platos', 'Do and make', 'B1'),
  ('Do exercise', 'hacer ejercicio', 'Do and make', 'B1'),
  ('Do body activities', 'hacer actividades corporales', 'Do and make', 'B1'),
  ('Do the shopping', 'hacer las compras', 'Do and make', 'B1'),
  ('Do the best', 'hacer lo mejor', 'Do and make', 'B1'),
  ('Do the cleaning', 'hacer la limpieza', 'Do and make', 'B1'),
  ('Do wonders', 'hacer maravillas', 'Do and make', 'B1'),
  ('It is hard to do', 'es difícil de hacer', 'Do and make', 'B1'),
  ('Do for a living', 'hacer para ganarse la vida', 'Do and make', 'B1'),
  ('Do well at', 'hacer bien en', 'Do and make', 'B1'),
  ('Do badly at', 'hacer mal en', 'Do and make', 'B1'),
  ('It does seem rather late', 'en efecto parece muy tarde', 'Do and make', 'B1'),
  ('They do work very hard', 'ellos si trabajan muy duro', 'Do and make', 'B1'),
  ('Make good / bad', 'hacer bien / mal', 'Do and make', 'B1'),
  ('Make the bed', 'hacer o arreglar la cama', 'Do and make', 'B1'),
  ('Make a face', 'hacer una cara', 'Do and make', 'B1'),
  ('Make something better / worse', 'hacer algo mejor / peor', 'Do and make', 'B1'),
  ('He was', 'él fue, él era, él estaba', 'Do and make', 'B1'),
  ('It was', 'era, fue, estaba', 'Do and make', 'B1'),
  ('You were', 'tu fuiste, tú eras, tu estabas, ustedes fueron, ustedes eran, ustedes estaban', 'Do and make', 'B1'),
  ('We were', 'nosotros fuimos, nosotros éramos, nosotros estábamos', 'Do and make', 'B1'),
  ('They were', 'ellos fueron, ellos eran, ellos estaban', 'Do and make', 'B1'),
  ('He was a teacher', 'él era un maestro', 'Do and make', 'B1'),
  ('We were enemies', 'nosotros éramos / fuimos enemigos', 'Do and make', 'B1'),
  ('It wasn´t my pet', 'no era mi mascota', 'Do and make', 'B1'),
  ('Were you in his house yesterday?', 'estaban ustedes en su casa ayer?', 'Do and make', 'B1'),
  ('Yesterday', 'ayer', 'Do and make', 'B1'),
  ('Last night', 'la noche pasada', 'Do and make', 'B1'),
  ('Last week', 'la semana pasada', 'Do and make', 'B1'),
  ('Last month', 'el mes pasado', 'Do and make', 'B1'),
  ('Asked', 'pregunto, pidió', 'Do and make', 'B1'),
  ('Received', 'recibió', 'Do and make', 'B1'),
  ('Arrived', 'llegó', 'Do and make', 'B1'),
  ('Visited', 'visitó', 'Do and make', 'B1'),
  ('Passed', 'pasó', 'Do and make', 'B1'),
  ('Had', 'tuvo', 'Do and make', 'B1'),
  ('Told', 'dijo', 'Do and make', 'B1'),
  ('Went', 'fue', 'Do and make', 'B1'),
  ('Made', 'hice', 'Do and make', 'B1'),
  ('Speak', 'hablar', 'Do and make', 'B1'),
  ('Spoke', 'habló', 'Do and make', 'B1'),
  ('Said', 'dijo', 'Do and make', 'B1'),
  ('Ate', 'comió', 'Do and make', 'B1'),
  ('Felt', 'sintió', 'Do and make', 'B1'),
  ('Sang', 'cantó', 'Do and make', 'B1'),
  ('Did you tell me the truth?', '¿me dijiste la verdad?', 'Do and make', 'B1'),
  ('Did she kiss her boyfriend?', 'beso ella a su novio?', 'Do and make', 'B1'),
  ('Were we enjoying those meals?', '¿estábamos nosotros disfrutando esas comidas?', 'Futuro y pasado', 'B1'),
  ('Interrupciones Interruptions', 'interrupciones', 'Futuro y pasado', 'B1'),
  ('Question words with future and past', 'palabras interrogativas con futuro y pasado', 'Futuro y pasado', 'B1'),
  ('Tags with future and past', 'preguntas de confirmacion con futuro y pasado', 'Futuro y pasado', 'B1'),
  ('Used to, still, and anymore Used to', 'acostumbraba, solía', 'Futuro y pasado', 'B1'),
  ('Anymore', 'ya mas', 'Futuro y pasado', 'B1'),
  ('Do you play anymore?', 'juegas tu mas? = continuas jugando?', 'Futuro y pasado', 'B1'),
  ('A little while', 'un poco de tiempo, un ratito', 'Futuro y pasado', 'B1'),
  ('To be used to', 'estar acostumbrado, estar familiarizado. Después de el "to", una acción debe de ir con "ing"', 'Futuro y pasado', 'B1'),
  ('To be fond of', 'estar encariñado con/de; tener cariño a', 'Futuro y pasado', 'B1'),
  ('Pronombres indefinidos Indefinite pronouns', 'pronombres indefinidos', 'Futuro y pasado', 'B1'),
  ('Everybody', 'cada uno, todos, cada quien', 'Futuro y pasado', 'B1'),
  ('Everything', 'cada cosa, todas las cosas', 'Futuro y pasado', 'B1'),
  ('Everywhere', 'cada lugar, todas partes, todos los lugares', 'Futuro y pasado', 'B1'),
  ('They sent everybody an invitation', 'ellos enviaron a cada quien una invitación', 'Futuro y pasado', 'B1'),
  ('Did we like everything about it?', 'nos gusta todo acerca de eso?', 'Futuro y pasado', 'B1'),
  ('Noone', 'no uno, ninguno, nadie', 'Futuro y pasado', 'B1'),
  ('Nobody', 'no cuerpo, ninguno, nadie', 'Futuro y pasado', 'B1'),
  ('Nothing', 'no cosa, ninguna cosa, nada', 'Futuro y pasado', 'B1'),
  ('I saw nobody that I knew', 'yo no vi a nadie que yo conociera', 'Futuro y pasado', 'B1'),
  ('Was there noone in the room?', 'había nadie en el cuarto?', 'Futuro y pasado', 'B1'),
  ('She said nothing about your accident', 'ella dijo nada acerca de tu accidente', 'Futuro y pasado', 'B1'),
  ('Nothing makes me angrier than that!', '¡nada me hace mas enojado que eso!', 'Futuro y pasado', 'B1'),
  ('Somebody', 'algún cuerpo, alguien', 'Futuro y pasado', 'B1'),
  ('Something', 'alguna cosa, algo', 'Futuro y pasado', 'B1'),
  ('Somewhere', 'algún lugar, alguna parte', 'Futuro y pasado', 'B1'),
  ('He is somewhere in this room', 'él esta en alguna parte de este cuarto', 'Futuro y pasado', 'B1'),
  ('There is somebody there', 'hay alguien alla', 'Futuro y pasado', 'B1'),
  ('There is something I can´t remember', 'hay algo que yo no recuerdo', 'Futuro y pasado', 'B1'),
  ('Anyone', 'alguien', 'Futuro y pasado', 'B1'),
  ('Anybody', 'alguien', 'Futuro y pasado', 'B1'),
  ('Anything', 'alguna cosa, algo', 'Futuro y pasado', 'B1'),
  ('Anywhere', 'algún lugar', 'Futuro y pasado', 'B1'),
  ('Either you go or I go', 'o vas tú o voy yo', 'Futuro y pasado', 'B1'),
  ('Each', 'cada, cada uno', 'Futuro y pasado', 'B1'),
  ('Each one of you', 'cada uno de ustedes', 'Futuro y pasado', 'B1'),
  ('Anyone can do this, it is so easy', 'cualquiera puede hacer esto, es tan facil', 'Futuro y pasado', 'B1'),
  ('Pronombres relativos Relative pronouns', 'pronombres relativos', 'Futuro y pasado', 'B1'),
  ('From whom did you receive ti?', '¿de quién lo recibistes?', 'Futuro y pasado', 'B1'),
  ('The day, when she came, was very warm', 'el día, cuando ella vino, estaba muy calido', 'Futuro y pasado', 'B1'),
  ('Whatever', 'lo que sea, el que sea, cualquier "refiriendose a una cosa o animal"', 'Futuro y pasado', 'B1'),
  ('Whichever', 'cualquier, cualquiera que, cual sea "refiriendose a una cosa o animal"', 'Futuro y pasado', 'B1'),
  ('Whoever', 'quien sea, quienquiera "refiriendose a una persona"', 'Futuro y pasado', 'B1'),
  ('Whomever', 'quien sea, a quien sea', 'Futuro y pasado', 'B1'),
  ('Wherever', 'donde sea, donde sea que, donde quiera, donde quiera que', 'Futuro y pasado', 'B1'),
  ('Do whatever is necessary', 'haz lo que sea que sea necesario = haz lo que sea necesario', 'Futuro y pasado', 'B1'),
  ('Take whichever book you prefer', 'toma cualquier libro que prefieras', 'Futuro y pasado', 'B1'),
  ('You can choose whichever you like', 'tu puedes elegir cualquiera (cual sea', 'Futuro y pasado', 'B1'),
  ('I won´t answer the phone whoever calls', 'yo no contestare el telefono quienquiera (quien sea', 'Futuro y pasado', 'B1'),
  ('Whoever finds it can keep it', 'quienquiera / quien sea que lo encuentre puede quedarselo', 'Futuro y pasado', 'B1'),
  ('Whoever you are', 'quienquiera que seas', 'Futuro y pasado', 'B1'),
  ('Ask whoever you like', 'pregunta a quien sea/quienquiera que gustes', 'Futuro y pasado', 'B1'),
  ('Please, call me from wherever you are', 'por favor, llamame de dondesea que estes', 'Futuro y pasado', 'B1'),
  ('Each other', 'el uno al otro "intervienen 2 personas"', 'Futuro y pasado', 'B1'),
  ('One another', 'unos a/con otros, uno a/con otro "intervienen 3 o más personas', 'Futuro y pasado', 'B1'),
  ('They used to give each other many presents', 'ellos solian darse el uno al otro muchos regalos', 'Futuro y pasado', 'B1'),
  ('Neither...nor', 'ni...ni', 'Futuro y pasado', 'B1'),
  ('Neither he nor she was at home yesterday', 'ni el ni ella estaban en casa ayer', 'Futuro y pasado', 'B1'),
  ('Conectores o conjunciones Connectors or conjunctions', 'conectores o conjunciones', 'Conectores', 'B1'),
  ('Because of', 'a causa de, por causa de, debido a', 'Conectores', 'B1'),
  ('I didn´t buy them because of their danger', 'yo no los compre a causa de/ debido a su daño', 'Conectores', 'B1'),
  ('As though', 'como si', 'Conectores', 'B1'),
  ('Lately', 'ultimamente', 'Conectores', 'B1'),
  ('You are very pretty lately!', 'tu estas muy bonita ultimamente!', 'Conectores', 'B1'),
  ('I am very happy indeed to see that!', 'yo estoy muy feliz ciertamente por ver eso!', 'Conectores', 'B1'),
  ('Nearly', 'aproximadamente, por poco, casi', 'Conectores', 'B1'),
  ('I nearly fell down', 'yo casi o por poco me caí', 'Conectores', 'B1'),
  ('Twice', 'dos veces', 'Conectores', 'B1'),
  ('Besides', 'ademas, ademas de, aparte de', 'Conectores', 'B1'),
  ('Afterwards', 'después, más tarde', 'Conectores', 'B1'),
  ('They are sometimes beside me', 'ellos esta a veces junto a mí', 'Conectores', 'B1'),
  ('Yet', 'pero, sin embargo', 'Conectores', 'B1'),
  ('Don´t worry, yet you are the best', 'no te preocupes, aun tú eres el mejor', 'Conectores', 'B1'),
  ('Therefore', 'por lo tanto, por tanto', 'Conectores', 'B1'),
  ('According to', 'según, de acuerdo a', 'Conectores', 'B1'),
  ('You have to dress according to your age', 'tu tienes que vestir de acuerdo a tu edad', 'Conectores', 'B1'),
  ('Otherwise', 'sino, de otra forma, de otra manera', 'Conectores', 'B1'),
  ('Consequently', 'consecuentemente, por tanto', 'Conectores', 'B1'),
  ('Likewise', 'así mismo, igualmente', 'Conectores', 'B1'),
  ('Thorough', 'adj', 'Conectores', 'B1'),
  ('Present perfect', 'presente perfecto', 'Presente/Pasado perfecto', 'B2'),
  ('All day', 'todo el día', 'Presente/Pasado perfecto', 'B2'),
  ('Recently', 'recientemente', 'Presente/Pasado perfecto', 'B2'),
  ('She has gone to her house recently', 'ella ha ido a su casa recientemente', 'Presente/Pasado perfecto', 'B2'),
  ('He has written a letter to them lately', 'él ha escrito una carta a ellos ultimamente', 'Presente/Pasado perfecto', 'B2'),
  ('They haven´t been working hard recently', 'ellos no han estado trabajando duro recientemente', 'Presente/Pasado perfecto', 'B2'),
  ('Pasado perfecto y pasado perfecto continuo Past perfect', 'pasado perfecto', 'Presente/Pasado perfecto', 'B2'),
  ('When', 'cuando', 'Presente/Pasado perfecto', 'B2'),
  ('Until', 'hasta', 'Presente/Pasado perfecto', 'B2'),
  ('By the time', 'por/en el momento, al tiempo que', 'Presente/Pasado perfecto', 'B2'),
  ('He had told you that when you arrived', 'él te había dicho eso cuando tu llegaste', 'Presente/Pasado perfecto', 'B2'),
  ('Had we seen them before they saw us?', 'habíamos nosotros visto a ellos antes de que ellos nos vieran?', 'Presente/Pasado perfecto', 'B2'),
  ('Past perfect continuous', 'pasado perfecto continuo', 'Presente/Pasado perfecto', 'B2'),
  ('Verbos auxiliares o modales Auxiliary verbs or modals', 'verbos auxiliares o modales', 'Verbos modales', 'B2'),
  ('We shouldn´t kill animals or plants', 'nosotros no beberíamos matar animales o plantas', 'Verbos modales', 'B2'),
  ('Should I love everyone in the world?', '¿debería yo amar a cada uno en el mundo?', 'Verbos modales', 'B2'),
  ('He couldn´t afford the car which he liked', 'él no pudo pagar el carro que le gusto', 'Verbos modales', 'B2'),
  ('Modales en pasado Modals in past', 'modales en pasado', 'Verbos modales', 'B2'),
  ('They should have seen the doctor last month', 'ellos deberían haber visto el doctor el mes pasado', 'Verbos modales', 'B2'),
  ('Present unreal', 'presente irreal', 'Condicionales', 'B2'),
  ('Y future real', 'futuro real', 'Condicionales', 'B2'),
  ('To wish', 'desear', 'Estructuras avanzadas', 'B2'),
  ('To wish somebody to do something', 'desear que alguien haga algo', 'Estructuras avanzadas', 'B2'),
  ('The causative The causative', 'el causante', 'Estructuras avanzadas', 'B2'),
  ('Even', 'incluso', 'Estructuras avanzadas', 'B2'),
  ('Verbos y preposiciones Verbs and prepositions', 'verbos y preposiciones', 'Estructuras avanzadas', 'B2'),
  ('Plan on', 'planear "un asunto o acción"', 'Estructuras avanzadas', 'B2'),
  ('Rely on', 'contar con " que alguien hará algo"', 'Estructuras avanzadas', 'B2'),
  ('Inquire for', 'pedir información por, buscar', 'Estructuras avanzadas', 'B2'),
  ('Apply for', 'solicitar', 'Estructuras avanzadas', 'B2'),
  ('Remind of', 'recordar de alguien', 'Estructuras avanzadas', 'B2'),
  ('Count on', 'contar con', 'Estructuras avanzadas', 'B2'),
  ('Think of', 'pensar en', 'Estructuras avanzadas', 'B2'),
  ('Distinguish from', 'distingir de', 'Estructuras avanzadas', 'B2'),
  ('Change for', 'cambiar por', 'Estructuras avanzadas', 'B2'),
  ('Argue about', 'discutir acerca de', 'Estructuras avanzadas', 'B2'),
  ('Warn about', 'advertir de/acerca de', 'Estructuras avanzadas', 'B2'),
  ('Aim at', 'apuntar a', 'Estructuras avanzadas', 'B2'),
  ('Prevail against', 'prevalecer sobre', 'Estructuras avanzadas', 'B2'),
  ('Dress in', 'vestir de', 'Estructuras avanzadas', 'B2'),
  ('Laugh at', 'reir o reirse de', 'Estructuras avanzadas', 'B2'),
  ('Happy - unhappy', 'feliz - infeliz', 'Prefijos', 'B2'),
  ('Legal - illegal', 'legal - ilegal', 'Prefijos', 'B2'),
  ('Able - unable', 'capaz - incapaz', 'Prefijos', 'B2');